(()=>{
'use strict';
const HIGHLIGHT_STORE='alevel-textbook-highlights-v1',MASTERY_STORE='alevel-textbook-mastery-v1';let observer=null,applying=false,searchLayer=null,highlightLayer=null,lastSelection=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();const norm=s=>clean(s).toLowerCase().replace(/[×·]/g,'*').replace(/[−–—]/g,'-').replace(/[^a-z0-9λρφσεμνπτθωΩ^+\-*/=. ]+/gi,' ');
const data=()=>window.CourseTextbook?.data||{};const state=()=>window.CourseTextbook?.getState?.()||{};function cur(){const s=state(),topic=data()[s.topicId],index=Number(s.chapterIndex)||0;return{s,topic,chapter:topic?.chapters?.[index],index}}
function load(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}function save(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function chapterKey(topicId,index){return`${topicId}:${index}`}
function source(chapter){return clean([chapter?.title,chapter?.summary,...(chapter?.sections||[]).flat(),...(chapter?.equations||[]).flat(),...(chapter?.checks||[]),chapter?.examTip].filter(Boolean).join(' '))}
function first(text){const t=clean(text),m=t.match(/^(.+?[.!?])(?:\s|$)/);return(m?.[1]||t).slice(0,240)}
function allChapters(){const out=[];Object.entries(data()).forEach(([topicId,topic])=>(topic.chapters||[]).forEach((chapter,chapterIndex)=>out.push({topicId,topic,chapter,chapterIndex})));return out}
function searchIndex(){const items=[];allChapters().forEach(({topicId,topic,chapter,chapterIndex})=>{items.push({type:'chapter',topicId,chapterIndex,title:chapter.title,meta:`${topic.code} · ${topic.title}`,snippet:chapter.summary||'',hay:norm(source(chapter))});(chapter.sections||[]).forEach(([heading,body],sectionIndex)=>items.push({type:'section',topicId,chapterIndex,sectionIndex,title:heading,meta:`${topic.code} · ${chapter.title}`,snippet:first(body),hay:norm(`${heading} ${body}`)}));(chapter.equations||[]).forEach((eq,equationIndex)=>items.push({type:'equation',topicId,chapterIndex,equationIndex,title:eq[0],meta:`${topic.code} · ${chapter.title}`,snippet:`${eq[1]}${eq[2]?` · ${eq[2]}`:''}`,hay:norm(eq.join(' '))}));});const terms=window.CourseTextbook?.terms||{};Object.entries(terms).forEach(([term,info])=>{const match=allChapters().find(x=>norm(source(x.chapter)).includes(norm(term)));items.push({type:'term',topicId:match?.topicId||Object.keys(data())[0],chapterIndex:match?.chapterIndex||0,term,title:term,meta:'Physics glossary',snippet:info.d||'',hay:norm(`${term} ${info.d||''} ${info.more||''} ${info.equation||''}`)});});return items}
function resultsFor(query){const q=norm(query);if(q.length<2)return[];const terms=q.split(' ').filter(Boolean);return searchIndex().map(item=>{let score=0;if(item.hay.includes(q))score+=12;if(norm(item.title).includes(q))score+=15;terms.forEach(t=>{if(item.hay.includes(t))score+=2;if(norm(item.title).includes(t))score+=3});return{...item,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,24)}
function openResult(item){window.CourseTextbook?.open?.(item.topicId,item.chapterIndex);setTimeout(()=>{const article=document.getElementById('textbookArticle');if(item.type==='section')article?.querySelectorAll('.textbook-section')?.[item.sectionIndex]?.scrollIntoView({behavior:'smooth',block:'start'});else if(item.type==='equation')article?.querySelectorAll('.textbook-equation')?.[item.equationIndex]?.scrollIntoView({behavior:'smooth',block:'center'});else if(item.type==='term')window.CourseTextbook?.openTerm?.(item.term);closeSearch();},120)}
function ensureSearch(){if(searchLayer?.isConnected)return searchLayer;searchLayer=document.createElement('div');searchLayer.className='tbp6-search-layer';searchLayer.hidden=true;searchLayer.innerHTML=`<div class="tbp6-search-scrim" data-tbp6-close></div><section class="tbp6-search-panel" role="dialog" aria-modal="true" aria-label="Search Physics textbook"><header><div><span>Textbook search</span><h2>Find a concept, equation or chapter</h2></div><button type="button" data-tbp6-close aria-label="Close">×</button></header><label class="tbp6-searchbox"><span>⌕</span><input type="search" placeholder="Try: internal resistance, F = ma, half-life…" autocomplete="off"></label><div class="tbp6-search-hints"><button type="button" data-q="uncertainty">uncertainty</button><button type="button" data-q="photoelectric">photoelectric</button><button type="button" data-q="v = fλ">v = fλ</button><button type="button" data-q="internal resistance">internal resistance</button><button type="button" data-q="SHM">SHM</button></div><div class="tbp6-search-results" aria-live="polite"></div></section>`;document.body.appendChild(searchLayer);const input=searchLayer.querySelector('input'),out=searchLayer.querySelector('.tbp6-search-results');const render=()=>{const items=resultsFor(input.value);out.innerHTML=!input.value.trim()?'<div class="tbp6-search-empty">Search the complete AQA textbook, including equations and glossary definitions.</div>':items.length?items.map((x,i)=>`<button type="button" class="tbp6-search-result" data-result="${i}"><span class="tbp6-result-type">${esc(x.type)}</span><div><strong>${esc(x.title)}</strong><small>${esc(x.meta)}</small><p>${esc(x.snippet)}</p></div><b>→</b></button>`).join(''):'<div class="tbp6-search-empty">No matching textbook content found.</div>';out.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>openResult(items[Number(b.dataset.result)])));};input.addEventListener('input',render);searchLayer.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.q;render();input.focus()}));searchLayer.addEventListener('click',e=>{if(e.target.closest('[data-tbp6-close]'))closeSearch()});return searchLayer}
function openSearch(query=''){const layer=ensureSearch(),input=layer.querySelector('input');layer.hidden=false;document.body.classList.add('tbp6-modal-open');input.value=query;input.dispatchEvent(new Event('input'));setTimeout(()=>input.focus(),30)}function closeSearch(){if(!searchLayer)return;searchLayer.hidden=true;document.body.classList.remove('tbp6-modal-open')}
function highlights(){const v=load(HIGHLIGHT_STORE,[]);return Array.isArray(v)?v:[]}
function saveHighlights(items){save(HIGHLIGHT_STORE,items.slice(-250));window.dispatchEvent(new CustomEvent('textbookhighlightschange'));}
function currentHighlights(){const {s,index}=cur();return highlights().filter(h=>h.topicId===s.topicId&&Number(h.chapterIndex)===index)}
function addHighlight(text){const {s,topic,chapter,index}=cur();const value=clean(text);if(!topic||!chapter||value.length<4)return;const all=highlights();if(all.some(h=>h.topicId===s.topicId&&Number(h.chapterIndex)===index&&h.text===value))return;all.push({id:`h-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,topicId:s.topicId,chapterIndex:index,chapterTitle:chapter.title,code:topic.code,text:value.slice(0,1400),note:'',at:Date.now()});saveHighlights(all);applyHighlights();refreshTools()}
function deleteHighlight(id){saveHighlights(highlights().filter(h=>h.id!==id));applyHighlights();renderHighlightsPanel();refreshTools()}
function editHighlight(id){const all=highlights(),item=all.find(h=>h.id===id);if(!item)return;const value=window.prompt('Add a note to this highlight:',item.note||'');if(value===null)return;item.note=clean(value).slice(0,800);saveHighlights(all);renderHighlightsPanel()}
function saveHighlightToNotebook(id){const item=highlights().find(h=>h.id===id);if(!item)return;const topic=data()[item.topicId];window.CourseNotebook?.save?.(`${item.text}${item.note?`\n\nMy note: ${item.note}`:''}`,{topicId:item.topicId,code:topic?.code||item.code,title:topic?.title||'',moduleLabel:'Textbook highlight',sectionTitle:item.chapterTitle,pageTitle:'AQA Physics Textbook',sourceType:'selection'})}
function unwrapHighlights(article){article.querySelectorAll('mark[data-tbp6-highlight]').forEach(mark=>mark.replaceWith(document.createTextNode(mark.textContent)));article.normalize()}
function markText(article,item){const walker=document.createTreeWalker(article,NodeFilter.SHOW_TEXT,{acceptNode(node){if(!node.nodeValue?.trim())return NodeFilter.FILTER_REJECT;const p=node.parentElement;if(!p||p.closest('button,textarea,input,select,script,style,mark,.tbp6-mastery,.tbp6-top-tools'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});let node;while(node=walker.nextNode()){const raw=node.nodeValue,idx=raw.toLowerCase().indexOf(item.text.toLowerCase());if(idx<0)continue;const before=node.splitText(idx),after=before.splitText(item.text.length),mark=document.createElement('mark');mark.dataset.tbp6Highlight=item.id;mark.className='tbp6-highlight';mark.textContent=before.nodeValue;before.replaceWith(mark);return true}return false}
function applyHighlights(){const article=document.getElementById('textbookArticle');if(!article)return;unwrapHighlights(article);currentHighlights().forEach(item=>markText(article,item))}
function ensureHighlightPanel(){if(highlightLayer?.isConnected)return highlightLayer;highlightLayer=document.createElement('div');highlightLayer.className='tbp6-highlight-layer';highlightLayer.hidden=true;highlightLayer.innerHTML='<div class="tbp6-highlight-scrim" data-highlight-close></div><aside class="tbp6-highlight-panel"><header><div><span>Personal textbook</span><h2>Highlights & notes</h2></div><button type="button" data-highlight-close>×</button></header><div class="tbp6-highlight-list"></div></aside>';document.body.appendChild(highlightLayer);highlightLayer.addEventListener('click',e=>{if(e.target.closest('[data-highlight-close]')){highlightLayer.hidden=true;return}const row=e.target.closest('[data-highlight-id]');if(!row)return;const id=row.dataset.highlightId;if(e.target.closest('[data-h-jump]')){const h=highlights().find(x=>x.id===id);if(h){window.CourseTextbook?.open?.(h.topicId,Number(h.chapterIndex));setTimeout(()=>document.querySelector(`mark[data-tbp6-highlight="${CSS.escape(id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),120)}highlightLayer.hidden=true}else if(e.target.closest('[data-h-note]'))editHighlight(id);else if(e.target.closest('[data-h-save]'))saveHighlightToNotebook(id);else if(e.target.closest('[data-h-delete]'))deleteHighlight(id)});return highlightLayer}
function renderHighlightsPanel(){const layer=ensureHighlightPanel(),list=layer.querySelector('.tbp6-highlight-list'),items=highlights().slice().sort((a,b)=>b.at-a.at);list.innerHTML=items.length?items.map(h=>`<article data-highlight-id="${esc(h.id)}"><span>${esc(h.code||'')} · ${esc(h.chapterTitle)}</span><p>“${esc(h.text)}”</p>${h.note?`<div class="tbp6-personal-note">${esc(h.note)}</div>`:''}<div><button type="button" data-h-jump>Jump</button><button type="button" data-h-note>${h.note?'Edit note':'Add note'}</button><button type="button" data-h-save>Save to notebook</button><button type="button" data-h-delete>Delete</button></div></article>`).join(''):'<div class="tbp6-search-empty">Select useful textbook text and choose <strong>Highlight</strong> to build a personal revision collection.</div>'}
function openHighlights(){renderHighlightsPanel();ensureHighlightPanel().hidden=false}
function augmentSelectionBubble(){const bubble=document.querySelector('.tbp3-selection-bubble');if(!bubble||bubble.querySelector('[data-tbp6-highlight]'))return;bubble.insertAdjacentHTML('beforeend','<button type="button" data-tbp6-highlight>Highlight</button><button type="button" data-tbp6-note>Save note</button>');bubble.querySelector('[data-tbp6-highlight]').addEventListener('mousedown',e=>e.preventDefault());bubble.querySelector('[data-tbp6-note]').addEventListener('mousedown',e=>e.preventDefault());bubble.querySelector('[data-tbp6-highlight]').addEventListener('click',()=>{if(lastSelection?.text)addHighlight(lastSelection.text)});bubble.querySelector('[data-tbp6-note]').addEventListener('click',()=>{if(!lastSelection?.text)return;const {s,topic,chapter}=cur();window.CourseNotebook?.save?.(lastSelection.text,{topicId:s.topicId,code:topic?.code||'',title:topic?.title||'',moduleLabel:'Textbook',sectionTitle:chapter?.title||'',pageTitle:'AQA Physics Textbook',sourceType:'selection'})})}
function masteryState(){const v=load(MASTERY_STORE,{});return v&&typeof v==='object'?v:{}}
function setMasteryItem(id,checked){const all=masteryState(),key=chapterKey(state().topicId,Number(state().chapterIndex)||0),entry=all[key]||{checks:{}};entry.checks[id]=checked;entry.updatedAt=Date.now();all[key]=entry;save(MASTERY_STORE,all)}
function termKeys(chapter){const text=norm(source(chapter)),terms=window.CourseTextbook?.terms||{};return Object.keys(terms).filter(k=>text.includes(norm(k))).slice(0,8)}
function misconceptions(chapter){const terms=window.CourseTextbook?.terms||{},items=termKeys(chapter).map(k=>terms[k]?.exam).filter(Boolean);if(chapter.examTip)items.unshift(chapter.examTip);return[...new Set(items)].slice(0,4)}
function nextChapterTarget(){const {s,index}=cur(),topic=data()[s.topicId],chapters=topic?.chapters||[];if(index<chapters.length-1)return{topicId:s.topicId,index:index+1,label:chapters[index+1].title};const keys=Object.keys(data()),ti=keys.indexOf(s.topicId),nextTopic=data()[keys[ti+1]];return nextTopic?.chapters?.length?{topicId:keys[ti+1],index:0,label:`${nextTopic.title}: ${nextTopic.chapters[0].title}`}:null}
function ensureMastery(article,topic,chapter,index){let box=article.querySelector('.tbp6-mastery');if(box)return box;box=document.createElement('section');box.className='tbp6-mastery';const key=chapterKey(state().topicId,index),saved=masteryState()[key]?.checks||{},ideas=(chapter.sections||[]).slice(0,5),eqs=(chapter.equations||[]).slice(0,5),terms=termKeys(chapter).slice(0,6),traps=misconceptions(chapter),next=nextChapterTarget();const item=(id,label)=>`<label><input type="checkbox" data-mastery-id="${esc(id)}" ${saved[id]?'checked':''}><span>${esc(label)}</span></label>`;box.innerHTML=`<div class="tbp6-mastery-head"><div><span>End-of-chapter mastery</span><h2>Can you use this chapter independently?</h2><p>Check knowledge, equations, vocabulary and exam thinking before moving on.</p></div><span class="tbp6-master-badge">Mastery</span></div><div class="tbp6-mastery-grid"><article><h3>Core ideas</h3>${ideas.map((x,i)=>item(`idea-${i}`,x[0])).join('')}</article><article><h3>Equations</h3>${eqs.length?eqs.map((x,i)=>item(`eq-${i}`,`${x[0]} · ${x[1]}`)).join(''):'<p>No core calculation equation in this chapter.</p>'}</article><article><h3>Vocabulary</h3>${terms.length?terms.map((x,i)=>item(`term-${i}`,x)).join(''):'<p>Use the chapter terminology precisely.</p>'}</article><article><h3>Exam traps</h3>${traps.length?traps.map((x,i)=>item(`trap-${i}`,x)).join(''):'<p>Check assumptions, units and wording carefully.</p>'}</article></div><div class="tbp6-mastery-actions"><button type="button" data-tbp6-teach>✦ Teach me this chapter</button><button type="button" data-tbp6-retest>Adaptive mastery test</button><button type="button" data-tbp6-tutor>✦ Tutor diagnostic</button>${next?`<button type="button" data-tbp6-next>Next: ${esc(next.label)} →</button>`:''}</div>`;(article.querySelector('.textbook-chapter-actions')||article.lastElementChild)?.insertAdjacentElement('beforebegin',box);box.addEventListener('change',e=>{const input=e.target.closest('[data-mastery-id]');if(input)setMasteryItem(input.dataset.masteryId,input.checked)});box.addEventListener('click',e=>{if(e.target.closest('[data-tbp6-teach]'))window.ALEVEL_TEXTBOOK_PHASE3?.send?.('teach',article,{wholeChapter:true});else if(e.target.closest('[data-tbp6-retest]'))window.ALEVEL_TEXTBOOK_PHASE5?.startRetest?.(false);else if(e.target.closest('[data-tbp6-tutor]'))window.ALEVEL_TEXTBOOK_PHASE3?.send?.('diagnostic',article,{wholeChapter:true});else if(e.target.closest('[data-tbp6-next]')&&next)window.CourseTextbook?.open?.(next.topicId,next.index)});return box}
function jumpWeak(){const section=document.querySelector('.textbook-section.tbp5-recommended');if(section)section.scrollIntoView({behavior:'smooth',block:'start'});else document.querySelector('.tbp5-adaptive')?.scrollIntoView({behavior:'smooth',block:'start'})}
function ensureTools(){const workspace=document.getElementById('textbookWorkspace');if(!workspace)return null;let tools=workspace.querySelector('.tbp6-top-tools');if(tools)return tools;tools=document.createElement('div');tools.className='tbp6-top-tools';tools.innerHTML='<button type="button" data-tbp6-search>⌕ Search textbook <kbd>Ctrl K</kbd></button><button type="button" data-tbp6-weak>◎ Jump to weak area</button><button type="button" data-tbp6-highlights>★ My highlights <span data-tbp6-highlight-count>0</span></button><button type="button" data-tbp6-mastery-jump>✓ Mastery</button>';const wrap=document.getElementById('textbookContentWrap');(wrap||workspace.firstElementChild)?.insertAdjacentElement('beforebegin',tools);tools.addEventListener('click',e=>{if(e.target.closest('[data-tbp6-search]'))openSearch();else if(e.target.closest('[data-tbp6-weak]'))jumpWeak();else if(e.target.closest('[data-tbp6-highlights]'))openHighlights();else if(e.target.closest('[data-tbp6-mastery-jump]'))document.querySelector('.tbp6-mastery')?.scrollIntoView({behavior:'smooth',block:'start'})});return tools}
function refreshTools(){const tools=ensureTools(),count=tools?.querySelector('[data-tbp6-highlight-count]');if(count)count.textContent=String(currentHighlights().length)}
function apply(){if(applying)return;const article=document.getElementById('textbookArticle'),{topic,chapter,index}=cur();if(!article||!topic||!chapter)return;applying=true;try{ensureTools();ensureMastery(article,topic,chapter,index);applyHighlights();refreshTools()}finally{applying=false}}
function observe(){const article=document.getElementById('textbookArticle');if(!article)return;observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(article,{childList:true,subtree:true});apply()}
document.addEventListener('mouseup',()=>{const workspace=document.getElementById('textbookWorkspace');if(!workspace||workspace.hidden)return;const text=clean(window.getSelection()?.toString());if(text.length>=4&&text.length<=1400){lastSelection={text};setTimeout(augmentSelectionBubble,0)}});window.addEventListener('textbookhighlightschange',()=>{applyHighlights();refreshTools()});window.addEventListener('textbookchange',e=>{if(e.detail?.open)setTimeout(()=>{observe();apply()},120)});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&!document.getElementById('textbookWorkspace')?.hidden){e.preventDefault();openSearch()}else if(e.key==='Escape'&&searchLayer&&!searchLayer.hidden)closeSearch()});const start=()=>document.getElementById('textbookArticle')?observe():setTimeout(start,180);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
window.ALEVEL_TEXTBOOK_PHASE6={refresh:apply,search:openSearch,highlights:()=>highlights(),openHighlights};
})();