(()=>{
  'use strict';

  let observer=null;
  let applying=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
  const words=s=>clean(s).toLowerCase().replace(/[^a-z0-9α-ωλφρσεμνπτθ]+/g,' ').split(/\s+/).filter(w=>w.length>3);
  const state=()=>window.CourseTextbook?.getState?.()||{};
  const current=()=>{const s=state(),data=window.CourseTextbook?.data||{};const topic=data[s.topicId];return{s,topic,chapter:topic?.chapters?.[Number(s.chapterIndex)||0],index:Number(s.chapterIndex)||0};};
  const sourceFor=chapter=>clean([chapter?.title,chapter?.summary,...(chapter?.sections||[]).flat(),...(chapter?.equations||[]).flat(),chapter?.examTip].filter(Boolean).join(' ')).toLowerCase();

  const SKILLS={
    units:{title:'SI units & conversions',tag:'Core maths',why:'Convert quantities before substitution so equations stay dimensionally consistent.',example:'2.4 km = 2.4 × 10³ m',question:'Convert 3.2 μm to metres.',placeholder:'e.g. 3.2e-6',answer:3.2e-6,tolerance:1e-10,method:['micro (μ) means ×10⁻⁶','3.2 μm = 3.2 × 10⁻⁶ m','Keep the value in SI units for substitution.']},
    standard:{title:'Standard form',tag:'Core maths',why:'Very large and very small physics quantities are easier to compare and calculate in scientific notation.',example:'0.00045 = 4.5 × 10⁻⁴',question:'Write 0.000072 in standard form. Enter as a number.',placeholder:'e.g. 7.2e-5',answer:7.2e-5,tolerance:1e-9,method:['Move the decimal point until the first number is between 1 and 10.','The decimal moves 5 places to the right.','So the exponent is −5: 7.2 × 10⁻⁵.']},
    rearrange:{title:'Rearranging equations',tag:'Algebra',why:'Rearrange symbolically before substituting to reduce arithmetic and unit mistakes.',example:'F = ma  →  a = F/m',question:'For F = 18 N and m = 3.0 kg, calculate a in m s⁻².',placeholder:'number only',answer:6,tolerance:.01,method:['Start with F = ma.','Divide both sides by m: a = F/m.','a = 18/3.0 = 6.0 m s⁻².']},
    proportionality:{title:'Proportional reasoning',tag:'Relationships',why:'Use proportionality to predict how one quantity changes before doing a full calculation.',example:'y ∝ x²: doubling x makes y four times larger.',question:'If y ∝ x² and x triples, by what factor does y change?',placeholder:'factor',answer:9,tolerance:.01,method:['The exponent is 2.','Tripling x gives 3².','Therefore y changes by a factor of 9.']},
    gradient:{title:'Gradients & intercepts',tag:'Graphs',why:'A graph gradient often represents a physical constant or combination of constants.',example:'gradient = Δy/Δx; units = y-units ÷ x-units',question:'A best-fit line changes by 12 units vertically for 3 units horizontally. Find the gradient.',placeholder:'number only',answer:4,tolerance:.01,method:['Use two well-separated points on the best-fit line.','gradient = Δy/Δx','12/3 = 4.']},
    uncertainty:{title:'Percentage uncertainty',tag:'Practical maths',why:'Uncertainty lets you judge whether a result is precise enough to support a conclusion.',example:'% uncertainty = absolute uncertainty ÷ measured value × 100',question:'A value is 10.0 ± 0.2. Find the percentage uncertainty.',placeholder:'percent',answer:2,tolerance:.05,method:['0.2/10.0 = 0.02','Multiply by 100.','Percentage uncertainty = 2.0%.']},
    vectors:{title:'Vectors & components',tag:'Mechanics maths',why:'Resolve vectors into perpendicular components before combining forces or velocities.',example:'R = √(x² + y²) for perpendicular components',question:'Perpendicular components are 3 N and 4 N. Find the resultant magnitude.',placeholder:'N',answer:5,tolerance:.01,method:['Square each component.','Add: 3² + 4² = 25.','Square-root: R = 5 N.']},
    trig:{title:'Trigonometry',tag:'Geometry',why:'Many A-level relationships use the component of a vector perpendicular or parallel to another direction.',example:'component = F sinθ or F cosθ depending on the defined angle',question:'Calculate sin 30°.',placeholder:'number',answer:.5,tolerance:.01,method:['Check the angle is defined from the correct reference direction.','sin 30° = 0.5.','Use degrees unless the equation specifically requires radians.']},
    radians:{title:'Radians',tag:'Further mechanics',why:'Angular equations such as v = ωr and ω = 2πf use angles measured in radians.',example:'180° = π rad',question:'Convert 90° to radians. Give a decimal value.',placeholder:'radians',answer:Math.PI/2,tolerance:.02,method:['Multiply degrees by π/180.','90 × π/180 = π/2.','π/2 ≈ 1.57 rad.']},
    logs:{title:'Logarithms & linearisation',tag:'Data maths',why:'Logs can turn power laws and exponentials into straight-line forms whose gradients have physical meaning.',example:'y = axⁿ → log y = log a + n log x',question:'For a log-log graph of y against x with gradient 2.5, what is n in y = axⁿ?',placeholder:'n',answer:2.5,tolerance:.01,method:['Compare log y = log a + n log x with y = mx + c.','The graph gradient equals n.','So n = 2.5.']},
    exponential:{title:'Exponentials & half-life',tag:'A-level maths',why:'Capacitor discharge and radioactive decay change by a fixed fraction rather than a fixed amount.',example:'y = y₀e⁻ᵗ/τ or N = N₀(1/2)ᵗ/ᵀ½',question:'What fraction remains after 3 half-lives?',placeholder:'decimal fraction',answer:.125,tolerance:.005,method:['Each half-life multiplies the amount by 1/2.','After 3 half-lives: (1/2)³.','The remaining fraction is 1/8 = 0.125.']}
  };

  function skillsFor(topicId,chapter){
    const src=sourceFor(chapter),chosen=[];
    const add=k=>{if(SKILLS[k]&&!chosen.includes(k))chosen.push(k);};
    if(/uncertaint|error|precision|measurement|gradient|graph/.test(src)){add('uncertainty');add('gradient');}
    if(/logarith|power law|linear/.test(src))add('logs');
    if(/exponential|half-life|decay|capacitor|time constant/.test(src))add('exponential');
    if(/vector|force|projectile|moment|equilibrium|field|magnetic/.test(src)){add('vectors');add('trig');}
    if(/angular|circular|radian|simple harmonic|shm/.test(src))add('radians');
    if(/proportion|inverse|square|resist|wave|field|gas|pressure|density/.test(src))add('proportionality');
    if(/equation|calculate|energy|power|momentum|current|potential|stress|strain|photon/.test(src))add('rearrange');
    if(/prefix|unit|metre|millimet|micro|nano|area|volume/.test(src))add('units');
    if(/10⁻|10\^|standard form|order of magnitude|photon|nuclear|atomic/.test(src))add('standard');
    if(topicId==='measurements'){add('units');add('uncertainty');add('gradient');}
    if(topicId==='mechanics-materials'){add('vectors');add('rearrange');add('trig');}
    if(topicId==='further-mechanics'){add('radians');add('rearrange');}
    if(topicId==='nuclear'){add('standard');add('exponential');}
    if(chosen.length<3){add('rearrange');add('units');add('proportionality');}
    return chosen.slice(0,4);
  }

  function markNumeric(input,skill){
    const raw=String(input||'').trim().replace(/×/g,'*').replace(/\s+/g,'');
    if(!raw)return{ok:false,message:'Enter an answer first.'};
    let value=Number(raw.replace(/\^/g,'**'));
    if(!Number.isFinite(value)){
      const sci=raw.match(/^([+-]?\d*\.?\d+)[x*]?10\^?([+-]?\d+)$/i);
      if(sci)value=Number(sci[1])*Math.pow(10,Number(sci[2]));
    }
    if(!Number.isFinite(value))return{ok:false,message:'Use a numerical answer. Scientific notation such as 3.2e-6 is accepted.'};
    const tol=Math.max(skill.tolerance||.01,Math.abs(skill.answer)*(skill.tolerance||.01));
    return Math.abs(value-skill.answer)<=tol?{ok:true,message:'Correct. Your numerical result matches the target.'}:{ok:false,message:'Not quite. Check the method, powers of ten and units, then try again.'};
  }

  function addMathsMastery(article,topicId,chapter){
    if(article.querySelector('.tbp4-maths'))return;
    const keys=skillsFor(topicId,chapter);if(!keys.length)return;
    const section=document.createElement('section');section.className='tbp4-maths';section.innerHTML=`<div class="tbp4-head"><div><span>Maths you need</span><h2>Master the maths behind this chapter</h2><p>Short refreshers target the mathematical skills used by the physics on this page.</p></div><span class="tbp4-badge">${keys.length} skills</span></div><div class="tbp4-skill-tabs">${keys.map((k,i)=>`<button type="button" data-tbp4-skill="${k}" aria-pressed="${i===0}">${esc(SKILLS[k].title)}</button>`).join('')}</div><div class="tbp4-skill-stage" data-tbp4-stage></div>`;
    const anchor=article.querySelector('.tbp3-chapter-tutor')||article.querySelector('.tbp1-overview')||article.querySelector('.textbook-terminology');anchor?.insertAdjacentElement('afterend',section);
    const stage=section.querySelector('[data-tbp4-stage]');
    const render=key=>{
      const skill=SKILLS[key];if(!skill)return;
      section.querySelectorAll('[data-tbp4-skill]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tbp4Skill===key?'true':'false'));
      stage.innerHTML=`<article class="tbp4-skill-card"><div class="tbp4-skill-copy"><span>${esc(skill.tag)}</span><h3>${esc(skill.title)}</h3><p>${esc(skill.why)}</p><div class="tbp4-example"><b>Example</b><code>${esc(skill.example)}</code></div></div><div class="tbp4-practice"><span>Quick practice</span><strong>${esc(skill.question)}</strong><div><input type="text" inputmode="decimal" placeholder="${esc(skill.placeholder)}" aria-label="Answer"><button type="button" data-tbp4-check>Check</button></div><p class="tbp4-feedback" data-tbp4-feedback hidden></p><details><summary>Show method</summary><ol>${skill.method.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></details><button type="button" class="tbp4-tutor" data-tbp4-maths-tutor>✦ Ask Tutor about this maths</button></div></article>`;
      stage.querySelector('[data-tbp4-check]').addEventListener('click',()=>{const input=stage.querySelector('input'),feedback=stage.querySelector('[data-tbp4-feedback]'),result=markNumeric(input.value,skill);feedback.hidden=false;feedback.classList.toggle('correct',result.ok);feedback.classList.toggle('retry',!result.ok);feedback.textContent=result.message;});
      stage.querySelector('input').addEventListener('keydown',e=>{if(e.key==='Enter')stage.querySelector('[data-tbp4-check]').click();});
      stage.querySelector('[data-tbp4-maths-tutor]').addEventListener('click',()=>window.ALEVEL_TEXTBOOK_PHASE3?.send?.('explain',stage.querySelector('.tbp4-skill-card')));
    };
    section.querySelectorAll('[data-tbp4-skill]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.tbp4Skill)));render(keys[0]);
  }

  function graphAdvice(topicId,chapter){
    const src=sourceFor(chapter);
    if(/exponential|half-life|decay|capacitor|time constant/.test(src))return{model:'Exponential relationship',axes:'Plot the measured quantity against time first. A straight-line transformation can then be used where appropriate.',linear:'For y = y₀e⁻ᵏᵗ, plotting ln y against t gives gradient −k.',gradient:'The gradient of the transformed graph gives the decay/discharge constant with units of inverse time.',uncertainty:'Use repeated readings where possible and judge whether scatter changes the fitted gradient significantly.'};
    if(/inverse.square|gravitational|electric field|radiation.*distance/.test(src))return{model:'Inverse-square relationship',axes:'Plot field strength or corrected count rate against distance, then test the predicted relationship.',linear:'A plot against 1/r² should be linear if the inverse-square model is appropriate.',gradient:'Interpret the gradient as the proportionality constant for the chosen variables.',uncertainty:'Distance uncertainty becomes increasingly important at small separations; use uncertainty bars where they are meaningful.'};
    if(/power law|logarith/.test(src))return{model:'Power-law relationship',axes:'A direct plot may be curved even when the model is correct.',linear:'For y = axⁿ, plot log y against log x. The gradient gives n.',gradient:'Gradient = n; intercept = log a.',uncertainty:'Do not overstate precision in n; compare the gradient uncertainty with expected integer or theoretical values.'};
    if(/stress|strain|hooke|young/.test(src))return{model:'Gradient gives a material property',axes:'Use stress on the vertical axis and strain on the horizontal axis for Young modulus.',linear:'Fit the initial proportional region only.',gradient:'Initial gradient = Young modulus, with units Pa.',uncertainty:'Diameter uncertainty matters strongly because cross-sectional area depends on diameter squared.'};
    if(/emf|internal resistance/.test(src))return{model:'Straight-line source model',axes:'Plot terminal p.d. V against current I.',linear:'V = ε − Ir matches y = c + mx.',gradient:'Intercept = ε; gradient = −r.',uncertainty:'Use a wide current range without exceeding safe component limits and include scatter in the best-fit judgement.'};
    return{model:'Best-fit relationship',axes:'Put the independent variable on the horizontal axis and the dependent variable on the vertical axis.',linear:'Compare the equation with y = mx + c or choose a justified transformation.',gradient:'Use a large triangle on the best-fit line and attach units from y-units ÷ x-units.',uncertainty:'Use error bars when appropriate and compare extreme acceptable gradients if gradient uncertainty is required.'};
  }

  function addGraphClinic(article,topicId,chapter){
    if(article.querySelector('.tbp4-graph-clinic'))return;const a=graphAdvice(topicId,chapter);
    const section=document.createElement('section');section.className='tbp4-graph-clinic';section.innerHTML=`<div class="tbp4-head"><div><span>Graph & data clinic</span><h2>${esc(a.model)}</h2><p>Turn practical data into evidence rather than just drawing a graph.</p></div><button type="button" data-tbp4-graph-tutor>✦ Tutor me</button></div><div class="tbp4-data-grid"><article><b>1 · Axes</b><p>${esc(a.axes)}</p></article><article><b>2 · Linearise</b><p>${esc(a.linear)}</p></article><article><b>3 · Gradient</b><p>${esc(a.gradient)}</p></article><article><b>4 · Uncertainty</b><p>${esc(a.uncertainty)}</p></article></div><div class="tbp4-graph-check"><strong>Graph checklist</strong><label><input type="checkbox"> axes labelled with quantity and unit</label><label><input type="checkbox"> sensible scale using most of the plotting area</label><label><input type="checkbox"> best-fit line/curve rather than dot-to-dot</label><label><input type="checkbox"> gradient taken from a large triangle on the fit</label></div>`;
    const anchor=article.querySelector('.textbook-equations')||article.querySelector('.tbp2-interactive')||article.querySelector('.textbook-example');anchor?.insertAdjacentElement('afterend',section);
    section.querySelector('[data-tbp4-graph-tutor]').addEventListener('click',()=>window.ALEVEL_TEXTBOOK_PHASE3?.send?.('explain',section));
  }

  function practicalLesson(topicId,chapter){
    const all=(window.ALEVEL_LESSONS||[]).filter(l=>l.topicId===topicId&&l.type==='practical');if(!all.length)return null;
    const query=new Set(words(`${chapter.title} ${chapter.summary}`));let best=null,score=-1;
    all.forEach(l=>{const s=words(`${l.title} ${l.focus}`).reduce((n,w)=>n+(query.has(w)?2:0),0);if(s>score){score=s;best=l;}});
    const src=sourceFor(chapter);const obvious=/practical|experiment|measure|graph|uncertaint|wave|interference|diffraction|young|resistiv|internal resistance|shm|gas|capacitor|magnetic|induction|radioactiv|inverse.square/.test(src);
    return score>0||obvious?best:null;
  }

  function practicalProfile(topicId,chapter,lesson){
    const src=sourceFor(chapter);
    const base={title:lesson?.title||'Practical investigation',aim:lesson?.focus||`Investigate a measurable relationship linked to ${chapter.title}.`,independent:'Choose one quantity to vary systematically.',dependent:'Measure the responding quantity with a suitable instrument.',controls:['Keep other variables that affect the relationship constant.','Use a consistent measurement method throughout.'],apparatus:['Suitable measuring instruments','Data table or digital recording method'],graph:'Plot the dependent variable against the independent variable or a justified transformed variable.',processing:['Repeat measurements where useful.','Calculate derived quantities in SI units.','Use a best-fit relationship rather than joining points.'],evaluation:['Identify the largest realistic source of uncertainty.','Suggest a specific change that would improve the quality of the evidence.'],safety:'Follow normal classroom risk assessment and teacher/technician instructions.'};
    if(topicId==='waves')return{...base,title:lesson?.title||'Wave investigation',independent:/diffraction|grating|double|interference/.test(src)?'Geometry or wavelength-related variable specified by the investigation.':'String length, tension, frequency or another defined wave variable.',dependent:'Measure fringe position, resonant frequency, wavelength or another observable wave quantity.',apparatus:['Appropriate wave source','Ruler/metre rule or position scale','Screen/string/resonant system as appropriate'],graph:'Choose a graph that makes the predicted wave relationship linear where possible.',processing:['Use repeated position measurements over several fringes/nodes to reduce percentage uncertainty.','Convert all distances to SI units before calculation.'],evaluation:['Reduce parallax when reading positions.','Use a larger measured interval where possible to reduce percentage uncertainty.']};
    if(topicId==='mechanics-materials'&&/young|stress|strain|elastic/.test(src))return{...base,title:lesson?.title||'Young modulus investigation',independent:'Applied force/load within the teacher-approved elastic range.',dependent:'Extension of the test wire or material.',controls:['Original length','Material and wire diameter','Temperature where relevant'],apparatus:['Test wire/material','Length scale','Diameter measuring instrument','Approved load/force arrangement'],graph:'Plot stress against strain; the gradient of the initial linear region gives Young modulus.',processing:['Use several diameter readings to estimate cross-sectional area.','Calculate stress F/A and strain ΔL/L in SI units.'],evaluation:['Diameter uncertainty has a large effect because area depends on diameter squared.','Use a long original length where appropriate to improve fractional extension measurement.']};
    if(topicId==='mechanics-materials')return{...base,title:lesson?.title||'Mechanics investigation',independent:'Defined motion or force variable.',dependent:'Time, displacement, velocity or acceleration.',apparatus:['Motion/timing system','Measured distance scale','Stable release/support arrangement'],graph:'Use the graph form predicted by the motion model; obtain g or another constant from a gradient when appropriate.',processing:['Repeat timings or use electronic timing where available.','Use the fitted gradient rather than a single pair of raw points.'],evaluation:['Reduce reaction-time effects with electronic timing or longer intervals.','State how alignment and release conditions affect systematic error.']};
    if(topicId==='electricity'&&/resistiv/.test(src))return{...base,title:lesson?.title||'Resistivity investigation',independent:'Length of a uniform conducting sample.',dependent:'Resistance found from measured current and potential difference.',controls:['Material','Temperature','Cross-sectional area'],apparatus:['Low-voltage circuit','Ammeter/current sensor','Voltmeter/voltage sensor','Uniform test wire and length scale','Diameter measuring instrument'],graph:'Plot resistance R against length L; gradient = ρ/A.',processing:['Calculate R = V/I for each length.','Use repeated diameter readings and A = πd²/4.'],evaluation:['Limit heating so resistivity is not changed by temperature.','Diameter uncertainty can dominate because area depends on d².']};
    if(topicId==='electricity'&&/internal resistance|emf/.test(src))return{...base,title:lesson?.title||'EMF and internal resistance investigation',independent:'Circuit current, varied using the approved circuit arrangement.',dependent:'Terminal potential difference.',controls:['Same cell/source','Temperature and measurement arrangement'],apparatus:['Low-voltage cell/source','Ammeter/current sensor','Voltmeter/voltage sensor','Variable load/resistance'],graph:'Plot terminal p.d. V against current I. Intercept = emf and gradient = −internal resistance.',processing:['Fit a straight line to V–I data.','Use the intercept for emf and magnitude of gradient for r.'],evaluation:['Avoid prolonged large currents that change source temperature/state.','Use a useful spread of current values while following equipment limits.']};
    if(topicId==='further-mechanics'&&/simple harmonic|shm|oscillat|pendulum|spring/.test(src))return{...base,title:lesson?.title||'SHM investigation',independent:'Oscillating-system variable such as length or mass, depending on the model.',dependent:'Period measured over several oscillations.',controls:['Small amplitude where the model requires it','Same release method','Same apparatus geometry except the chosen independent variable'],apparatus:['Oscillating system','Timing method','Length/mass measuring equipment'],graph:'Use a transformed graph such as T² against the appropriate independent variable when predicted by the model.',processing:['Time several oscillations then divide to obtain one period.','Repeat timings and calculate a mean.'],evaluation:['Longer total timing reduces percentage timing uncertainty.','Keep amplitude within the model assumptions.']};
    if(topicId==='further-mechanics'&&/gas|pressure|volume|temperature/.test(src))return{...base,title:lesson?.title||'Gas-law investigation',independent:'One gas variable such as volume or absolute temperature.',dependent:'The corresponding pressure/volume response.',controls:['Fixed amount of gas','A second state variable held constant where required by the law'],apparatus:['Sealed gas apparatus approved for classroom use','Pressure/volume/temperature sensors as appropriate'],graph:'Choose a graph or transformation that tests the predicted gas-law proportionality.',processing:['Use kelvin for temperature calculations.','Allow readings to stabilise before recording.'],evaluation:['Check for leaks/systematic offsets.','Discuss whether thermal equilibrium was reached before each reading.']};
    if(topicId==='fields'&&/capacitor|capacitance|discharge|time constant/.test(src))return{...base,title:lesson?.title||'Capacitor discharge investigation',independent:'Elapsed time after discharge begins.',dependent:'Capacitor voltage or charge proxy.',controls:['Same capacitor and resistance for one run','Same initial voltage'],apparatus:['Low-voltage capacitor circuit','Approved resistor','Voltage sensor/data logger or voltmeter','Timing/data-capture system'],graph:'Plot V against t and, where appropriate, ln V against t to obtain a straight-line gradient.',processing:['Find the time constant from the curve or transformed gradient.','Compare repeated runs if available.'],evaluation:['Use data logging to improve temporal resolution.','Ensure the same initial condition before comparing runs.']};
    if(topicId==='fields'&&/magnetic|induction|flux/.test(src))return{...base,title:lesson?.title||'Electromagnetic investigation',independent:'Current, field strength, speed or geometry depending on the model being tested.',dependent:'Force or induced emf.',controls:['Orientation/angle unless deliberately varied','Same conductor/coil geometry'],apparatus:['Low-voltage electrical apparatus','Magnetic-field/coil arrangement','Appropriate force or voltage sensor'],graph:'Plot the measured response against the model variable expected to be proportional.',processing:['Record sign/direction as well as magnitude where relevant.','Use gradient and units to connect the data to the governing equation.'],evaluation:['Keep geometry aligned and reproducible.','Account for zero offsets and sensor resolution.']};
    if(topicId==='nuclear')return{...base,title:'Radiation data investigation',aim:'Use teacher-provided, simulated or pre-collected count-rate data to test decay or distance relationships safely.',independent:'Time or distance in the supplied/simulated dataset.',dependent:'Background-corrected count rate/activity proxy.',controls:['Use the same dataset conditions and counting interval.','Apply the same background correction consistently.'],apparatus:['Simulated or teacher-provided dataset','Spreadsheet/graphing tools','Distance values or timestamps supplied with the data'],graph:/distance|inverse/.test(src)?'Plot corrected count rate against distance and test an inverse-square transformation such as 1/r².':'Plot count rate/activity against time and test an exponential model.',processing:['Subtract background count rate where the dataset requires it.','Use Poisson-style counting uncertainty qualitatively or quantitatively only where taught/provided.'],evaluation:['Discuss random counting variation and background radiation.','Use longer counting intervals in a simulation/data-design discussion to reduce fractional counting variation.'],safety:'Student mode uses simulated, teacher-provided or pre-collected data only; it does not provide instructions for handling radioactive sources.'};
    return base;
  }

  function addPracticalMastery(article,topicId,chapter){
    if(article.querySelector('.tbp4-practical'))return;const lesson=practicalLesson(topicId,chapter);if(!lesson)return;const p=practicalProfile(topicId,chapter,lesson);
    const section=document.createElement('section');section.className='tbp4-practical';section.innerHTML=`<div class="tbp4-practical-head"><div><span>Practical mastery</span><h2>${esc(p.title)}</h2><p>${esc(p.aim)}</p></div><span>${esc(lesson?.ref||'AQA practical skills')}</span></div><div class="tbp4-practical-grid"><article><b>Variables</b><p><strong>Independent:</strong> ${esc(p.independent)}</p><p><strong>Dependent:</strong> ${esc(p.dependent)}</p><p><strong>Controls:</strong> ${esc(p.controls.join(' · '))}</p></article><article><b>Apparatus</b><ul>${p.apparatus.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article><b>Graph / evidence</b><p>${esc(p.graph)}</p></article><article><b>Processing</b><ul>${p.processing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article><b>Evaluation</b><ul>${p.evaluation.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article class="tbp4-safety"><b>Safety & supervision</b><p>${esc(p.safety)}</p></article></div><div class="tbp4-practical-actions"><button type="button" data-tbp4-plan>✦ Tutor: plan this investigation</button><button type="button" data-tbp4-eval>✦ Tutor: improve evaluation</button><button type="button" data-tbp4-lab>Open full Practical Lab →</button></div>`;
    const anchor=article.querySelector('.tbp2-sim-bridge')||article.querySelector('.textbook-check')||article.querySelector('.textbook-chapter-actions');anchor?.insertAdjacentElement('beforebegin',section);
    section.querySelector('[data-tbp4-plan]').addEventListener('click',()=>window.ALEVEL_TEXTBOOK_PHASE3?.send?.('explain',section));
    section.querySelector('[data-tbp4-eval]').addEventListener('click',()=>window.ALEVEL_TEXTBOOK_PHASE3?.send?.('exam',section));
    section.querySelector('[data-tbp4-lab]').addEventListener('click',()=>{window.CourseTextbook?.close?.();setTimeout(()=>document.querySelector('.course-tool-card[data-course-tool="practicals"], [data-course-tool="practicals"]')?.click(),30);});
  }

  function apply(){
    if(applying)return;const article=document.getElementById('textbookArticle');if(!article||!window.CourseTextbook)return;const {s,topic,chapter}=current();if(!topic||!chapter)return;
    applying=true;try{article.classList.add('tbp4-article');addMathsMastery(article,s.topicId,chapter);addGraphClinic(article,s.topicId,chapter);addPracticalMastery(article,s.topicId,chapter);}finally{applying=false;}
  }
  function observe(){const article=document.getElementById('textbookArticle');if(!article)return;observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(article,{childList:true,subtree:true});apply();}
  window.addEventListener('textbookchange',e=>{if(e.detail?.open)setTimeout(()=>{observe();apply();},70);});
  document.addEventListener('click',e=>{if(e.target.closest('#textbookNext,#textbookPrevious,.textbook-chapter-button'))setTimeout(apply,70);});
  const start=()=>{if(document.getElementById('textbookArticle'))observe();else setTimeout(start,160);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.ALEVEL_TEXTBOOK_PHASE4={refresh:apply,skillsFor,practicalProfile};
})();