(()=>{
'use strict';
const OPTION_KEY='alevel-physics-paper3-option-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const data=()=>window.CourseTextbook?.data||{};
const state=()=>window.CourseTextbook?.getState?.()||{};
const CORE=[
  ['measurements','3.1','Measurements and their errors'],['particles','3.2','Particles and radiation'],['waves','3.3','Waves'],['mechanics-materials','3.4','Mechanics and materials'],['electricity','3.5','Electricity'],['further-mechanics','3.6','Further mechanics and thermal physics'],['fields','3.7','Fields and their consequences'],['nuclear','3.8','Nuclear physics']
];
const OPTIONS=[
 ['astrophysics','3.9','Astrophysics'],['medical-physics','3.10','Medical physics'],['engineering-physics','3.11','Engineering physics'],['turning-points','3.12','Turning points in physics'],['electronics','3.13','Electronics']
];
let layer=null,observer=null,applying=false;
function option(){try{return localStorage.getItem(OPTION_KEY)||''}catch{return''}}
function setOption(v){try{localStorage.setItem(OPTION_KEY,v)}catch{}renderLayer();renderChapterCard()}
function readState(){return state().read||{}}
function topicRead(topicId){const topic=data()[topicId],chapters=topic?.chapters||[];const read=readState(),done=chapters.filter(c=>read[`${topicId}:${c.id}`]).length;return{done,total:chapters.length,pct:chapters.length?done/chapters.length:0}}
function topicEvidence(topicId){try{const models=window.ALEVEL_GUIDED_TUTOR?.models?.()||[],items=models.filter(m=>m.base?.topicId===topicId&&m.stats?.percent!=null);if(!items.length)return null;return items.reduce((n,m)=>n+m.stats.percent,0)/items.length}catch{return null}}
function paperFor(topicId,chapter){if(['astrophysics','medical-physics','engineering-physics','turning-points','electronics'].includes(topicId))return'Paper 3';if(['measurements','particles','waves','mechanics-materials','electricity'].includes(topicId))return'Paper 1';if(topicId==='further-mechanics'){const src=`${chapter?.title||''} ${chapter?.summary||''}`.toLowerCase();return /periodic|simple harmonic|shm|oscillation|resonance|circular/.test(src)?'Paper 1':'Paper 2'}if(['fields','nuclear'].includes(topicId))return'Paper 2';return'Core'}
function examNote(topicId,chapter){const paper=paperFor(topicId,chapter);if(paper==='Paper 1')return'Short/long response and multiple-choice preparation. Practical and maths skills can still be assessed in context.';if(paper==='Paper 2')return'Build on earlier core knowledge as well as this Year 13 content. Practical and data skills can be assessed in context.';if(paper==='Paper 3')return'Paper 3 Section B optional-topic preparation. One of sections 3.9–3.13 is entered alongside compulsory practical/data analysis.';return'AQA core content.'}
function current(){const s=state(),topic=data()[s.topicId],index=Number(s.chapterIndex)||0;return{s,topic,chapter:topic?.chapters?.[index],index}}
function ensureChapterCard(){const article=document.getElementById('textbookArticle');if(!article)return null;let card=article.querySelector('.tbp7-spec-card');if(card)return card;card=document.createElement('section');card.className='tbp7-spec-card';(article.querySelector('.tbp5-adaptive')||article.querySelector('.tbp1-overview')||article.firstElementChild)?.insertAdjacentElement('afterend',card);card.addEventListener('click',e=>{if(e.target.closest('[data-tbp7-map]'))openLayer();if(e.target.closest('[data-tbp7-paper3]'))openLayer('options')});return card}
function renderChapterCard(){const {s,topic,chapter}=current();if(!topic||!chapter)return;const card=ensureChapterCard();if(!card)return;const paper=paperFor(s.topicId,chapter),chosen=option();card.innerHTML=`<div><span>AQA specification map</span><strong>${esc(topic.code)} · ${esc(topic.title)}</strong><p>${esc(examNote(s.topicId,chapter))}</p></div><div class="tbp7-spec-actions"><span class="tbp7-paper">${esc(paper)}</span><button type="button" data-tbp7-map>Specification & exam map</button><button type="button" data-tbp7-paper3>${chosen?`Paper 3 option: ${esc(chosen)}`:'Choose Paper 3 option'}</button></div>`}
function topicCard([id,ref,title]){const r=topicRead(id),e=topicEvidence(id),paper=id==='further-mechanics'?'P1 + P2':['fields','nuclear'].includes(id)?'P2':'P1';return`<button type="button" class="tbp7-topic" data-topic="${esc(id)}"><div><span>AQA ${ref}</span><strong>${esc(title)}</strong><small>${paper}</small></div><div><b>${r.done}/${r.total}</b><span>${Math.round(r.pct*100)}% read${e==null?'':` · ${Math.round(e*100)}% evidence`}</span></div></button>`}
function optionCard([id,ref,title]){const r=topicRead(id),chosen=option()===title;return`<article class="tbp7-option-card ${chosen?'selected':''}"><button type="button" data-option="${esc(title)}" data-option-id="${esc(id)}" aria-pressed="${chosen?'true':'false'}"><span>AQA ${ref}</span><strong>${esc(title)}</strong><small>${chosen?'Selected for this device':'Choose this option'}</small></button><div><b>${r.done}/${r.total} chapters read</b><button type="button" data-open-option="${esc(id)}">Open textbook →</button></div></article>`}
function ensureLayer(){if(layer?.isConnected)return layer;layer=document.createElement('div');layer.className='tbp7-layer';layer.hidden=true;layer.innerHTML=`<div class="tbp7-scrim" data-close></div><section class="tbp7-panel" role="dialog" aria-modal="true" aria-label="AQA specification and exam map"><header><div><span>AQA Physics 7408</span><h2>Specification & exam map</h2><p>See how the core textbook connects to AQA papers and your Paper 3 option.</p></div><button type="button" data-close aria-label="Close">×</button></header><div class="tbp7-paper-grid"><article><span>Paper 1</span><strong>Core + periodic motion</strong><p>Sections 3.1–3.5 and 3.6.1 periodic motion.</p></article><article><span>Paper 2</span><strong>Thermal, fields & nuclear</strong><p>Sections 3.6.2, 3.7 and 3.8, with earlier core knowledge assumed.</p></article><article><span>Paper 3</span><strong>Practical/data + one option</strong><p>Compulsory practical/data analysis plus one option from 3.9–3.13.</p></article></div><section><div class="tbp7-section-head"><div><span>Core content</span><h3>Sections 3.1–3.8</h3></div><small>Textbook coverage</small></div><div class="tbp7-topics" data-topics></div></section><section id="tbp7Options"><div class="tbp7-section-head"><div><span>Paper 3 Section B</span><h3>Choose your optional topic</h3></div><small>All five textbooks included</small></div><p class="tbp7-option-note">Select the option your school teaches. Each option below now opens a complete integrated textbook and uses the same Tutor, search, mastery and adaptive tools as the core course.</p><div class="tbp7-options" data-options></div></section><footer><strong>Exam reminder</strong><span>Paper 3 also assesses compulsory practical skills and data analysis. Use the integrated Practical Lab alongside the option textbook.</span><button type="button" data-practicals>Open Practical Lab →</button></footer></section>`;document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeLayer();const t=e.target.closest('[data-topic]');if(t){window.CourseTextbook?.open?.(t.dataset.topic,0);closeLayer()}const o=e.target.closest('[data-option]');if(o){setOption(o.dataset.option);const id=o.dataset.optionId;if(id){window.CourseTextbook?.open?.(id,0);closeLayer()}}const open=e.target.closest('[data-open-option]');if(open){const id=open.dataset.openOption;const meta=OPTIONS.find(x=>x[0]===id);if(meta)setOption(meta[2]);window.CourseTextbook?.open?.(id,0);closeLayer()}if(e.target.closest('[data-practicals]')){closeLayer();window.CourseTextbook?.close?.();document.querySelector('[data-course-tool="practicals"]')?.click()}});return layer}
function renderLayer(){const l=ensureLayer();l.querySelector('[data-topics]').innerHTML=CORE.map(topicCard).join('');l.querySelector('[data-options]').innerHTML=OPTIONS.map(optionCard).join('')}
function openLayer(section=''){renderLayer();layer.hidden=false;document.body.classList.add('tbp7-open');if(section==='options')setTimeout(()=>layer.querySelector('#tbp7Options')?.scrollIntoView({block:'start'}),20)}function closeLayer(){if(!layer)return;layer.hidden=true;document.body.classList.remove('tbp7-open')}
function apply(){if(applying)return;const article=document.getElementById('textbookArticle');if(!article)return;applying=true;try{renderChapterCard()}finally{applying=false}}
function observe(){const a=document.getElementById('textbookArticle');if(!a)return;observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(a,{childList:true,subtree:true});apply()}
window.addEventListener('textbookchange',e=>{if(e.detail?.open)setTimeout(observe,80)});window.addEventListener('alevel:automark-updated',()=>setTimeout(renderLayer,50));const start=()=>document.getElementById('textbookArticle')?observe():setTimeout(start,180);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
window.ALEVEL_TEXTBOOK_PHASE7={open:openLayer,close:closeLayer,getOption:option,setOption};
})();