(()=>{
'use strict';
const SCALE_KEY='alevel-textbook-scale-v1';let observer=null,applying=false,healthLayer=null,live=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state=()=>window.CourseTextbook?.getState?.()||{};const data=()=>window.CourseTextbook?.data||{};
function current(){const s=state(),topic=data()[s.topicId],index=Number(s.chapterIndex)||0;return{s,topic,chapter:topic?.chapters?.[index],index}}
function announce(text){if(!live){live=document.createElement('div');live.className='tbp8-sr-live';live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');document.body.appendChild(live)}live.textContent='';setTimeout(()=>live.textContent=text,10)}
function scale(){try{return Math.max(.9,Math.min(1.25,Number(localStorage.getItem(SCALE_KEY)||1)))}catch{return 1}}
function setScale(value){const v=Math.max(.9,Math.min(1.25,Number(value)||1));try{localStorage.setItem(SCALE_KEY,String(v))}catch{}document.documentElement.style.setProperty('--tbp8-text-scale',v);document.querySelector('[data-tbp8-scale-value]')?.replaceChildren(document.createTextNode(`${Math.round(v*100)}%`));announce(`Textbook text size ${Math.round(v*100)} percent`)}
function connectionLabel(){return navigator.onLine?'Online':'Offline'}
function safeJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}
function exportStudy(){const {s,topic,chapter}=current(),read=s.read||{},highlights=safeJson('alevel-textbook-highlights-v1',[]),mastery=safeJson('alevel-textbook-mastery-v1',{}),depth=safeJson('alevel-textbook-depth-v1',{}),attempts=safeJson('alevel-lesson-automarking-v1',[]),option=(()=>{try{return localStorage.getItem('alevel-physics-paper3-option-v1')||'Not selected'}catch{return'Not selected'}})();const lines=['# AQA A-Level Physics Study Summary','',`Exported: ${new Date().toLocaleString()}`,'',`Current chapter: ${topic?.code||''} · ${chapter?.title||''}`,`Paper 3 option: ${option}`,'',`Marked attempts: ${Array.isArray(attempts)?attempts.length:0}`,`Saved highlights: ${Array.isArray(highlights)?highlights.length:0}`,'','## Textbook reading'];Object.entries(data()).forEach(([topicId,t])=>{const done=(t.chapters||[]).filter(c=>read[`${topicId}:${c.id}`]).length;lines.push(`- ${t.code} ${t.title}: ${done}/${t.chapters?.length||0} chapters read`)});lines.push('','## Saved depth choices');Object.entries(depth||{}).forEach(([k,v])=>lines.push(`- ${k}: ${v}`));lines.push('','## Mastery checklist progress');Object.entries(mastery||{}).forEach(([k,v])=>{const checks=Object.values(v?.checks||{});lines.push(`- ${k}: ${checks.filter(Boolean).length}/${checks.length} checked`)});if(Array.isArray(highlights)&&highlights.length){lines.push('','## Highlights');highlights.slice(-80).forEach(h=>{lines.push(`- ${h.code||''} ${h.chapterTitle||''}: ${h.text}${h.note?` — Note: ${h.note}`:''}`)})}const blob=new Blob([lines.join('\n')],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`aqa-physics-study-summary-${new Date().toISOString().slice(0,10)}.md`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Study summary exported')}
function checks(){return[
  ['Textbook data',Object.keys(data()).length>=8,`${Object.keys(data()).length} topic data sets`],
  ['Adaptive learning',!!window.ALEVEL_TEXTBOOK_PHASE5,'Phase 5 status and re-testing'],
  ['Search & personal textbook',!!window.ALEVEL_TEXTBOOK_PHASE6,'Phase 6 search/highlights/mastery'],
  ['AQA exam map',!!window.ALEVEL_TEXTBOOK_PHASE7,'Phase 7 specification map'],
  ['Tutor',!!window.ALEVEL_AI_TUTOR,'Online/offline tutor API available in UI'],
  ['Auto-marking',!!window.ALEVEL_AUTOMARK,'Indicative local marking'],
  ['Guided dashboard',!!window.ALEVEL_GUIDED_TUTOR,'Weak-area course guidance'],
  ['Notebook',!!window.CourseNotebook,'Personal notes and exports'],
  ['Service worker',('serviceWorker' in navigator),navigator.serviceWorker?.controller?'Offline controller active':'Supported; controller activates after load/reload']
]}
function ensureHealth(){if(healthLayer?.isConnected)return healthLayer;healthLayer=document.createElement('div');healthLayer.className='tbp8-health-layer';healthLayer.hidden=true;healthLayer.innerHTML=`<div class="tbp8-health-scrim" data-close></div><section class="tbp8-health-panel" role="dialog" aria-modal="true" aria-label="Course system health"><header><div><span>Final QA</span><h2>Textbook system health</h2><p>Checks that the major course systems are loaded in this browser.</p></div><button type="button" data-close aria-label="Close">×</button></header><div class="tbp8-health-list" data-health-list></div><footer><strong data-health-summary></strong><span>This verifies loaded components, not the correctness of every individual physics answer or browser interaction.</span></footer></section>`;document.body.appendChild(healthLayer);healthLayer.addEventListener('click',e=>{if(e.target.closest('[data-close]'))healthLayer.hidden=true});return healthLayer}
function openHealth(){const l=ensureHealth(),items=checks(),pass=items.filter(x=>x[1]).length;l.querySelector('[data-health-list]').innerHTML=items.map(([name,ok,detail])=>`<article class="${ok?'pass':'warn'}"><span>${ok?'✓':'!'}</span><div><strong>${esc(name)}</strong><small>${esc(detail)}</small></div></article>`).join('');l.querySelector('[data-health-summary]').textContent=`${pass}/${items.length} systems available`;l.hidden=false;l.querySelector('[data-close]')?.focus()}
function ensureTools(){const article=document.getElementById('textbookArticle');if(!article)return null;let tools=article.querySelector('.tbp8-final-tools');if(tools)return tools;tools=document.createElement('nav');tools.className='tbp8-final-tools';tools.setAttribute('aria-label','Textbook display and course tools');tools.innerHTML=`<div class="tbp8-display"><span>Reading</span><button type="button" data-tbp8-smaller aria-label="Decrease textbook text size">A−</button><b data-tbp8-scale-value>${Math.round(scale()*100)}%</b><button type="button" data-tbp8-larger aria-label="Increase textbook text size">A+</button><button type="button" data-tbp8-reset>Reset</button></div><div class="tbp8-actions"><span class="tbp8-connection" data-tbp8-connection>${connectionLabel()}</span><button type="button" data-tbp8-spec>Exam map</button><button type="button" data-tbp8-print>Print chapter</button><button type="button" data-tbp8-export>Export study summary</button><button type="button" data-tbp8-health>System check</button></div>`;const anchor=article.querySelector('.tbp6-top-tools')||article.firstElementChild;anchor?.insertAdjacentElement(anchor.classList?.contains('tbp6-top-tools')?'afterend':'beforebegin',tools);tools.addEventListener('click',e=>{if(e.target.closest('[data-tbp8-smaller]'))setScale(scale()-.05);if(e.target.closest('[data-tbp8-larger]'))setScale(scale()+.05);if(e.target.closest('[data-tbp8-reset]'))setScale(1);if(e.target.closest('[data-tbp8-spec]'))window.ALEVEL_TEXTBOOK_PHASE7?.open?.();if(e.target.closest('[data-tbp8-print]'))window.print();if(e.target.closest('[data-tbp8-export]'))exportStudy();if(e.target.closest('[data-tbp8-health]'))openHealth()});return tools}
function updateConnection(){document.querySelectorAll('[data-tbp8-connection]').forEach(el=>{el.textContent=connectionLabel();el.dataset.state=navigator.onLine?'online':'offline'});announce(connectionLabel())}
function apply(){if(applying)return;const article=document.getElementById('textbookArticle');if(!article)return;applying=true;try{ensureTools();setScale(scale());article.setAttribute('data-tbp8-ready','1')}finally{applying=false}}
function observe(){const a=document.getElementById('textbookArticle');if(!a)return;observer?.disconnect();observer=new MutationObserver(()=>requestAnimationFrame(apply));observer.observe(a,{childList:true,subtree:true});apply()}
window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);window.addEventListener('textbookchange',e=>{if(e.detail?.open)setTimeout(observe,100)});document.addEventListener('keydown',e=>{const open=!document.getElementById('textbookWorkspace')?.hidden;if(!open)return;if(e.altKey&&e.key.toLowerCase()==='e'){e.preventDefault();window.ALEVEL_TEXTBOOK_PHASE7?.open?.()}if(e.altKey&&e.key.toLowerCase()==='q'){e.preventDefault();openHealth()}if(e.altKey&&e.key.toLowerCase()==='p'){e.preventDefault();window.print()}});const start=()=>document.getElementById('textbookArticle')?observe():setTimeout(start,180);document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();
window.ALEVEL_TEXTBOOK_PHASE8={refresh:apply,health:checks,openHealth,exportStudy,setScale};
})();