(()=>{
'use strict';
const D=window.PhysicsTextbookData=window.PhysicsTextbookData||{};
const c=(id,title,summary,sections,equations=[],example=null,examTip='',checks=[])=>({id,title,summary,sections,equations,example,examTip,checks});

D.astrophysics={code:'AQA 3.9',title:'Astrophysics',year:'Year 13 · Paper 3 option',option:true,chapters:[
 c('astro-telescopes','1. Telescopes and astronomical detection','Understand how optical and non-optical telescopes collect radiation and resolve detail.',[
  ['Refracting and reflecting telescopes','In normal adjustment a refracting telescope uses two converging lenses so the final image is effectively at infinity. Reflecting telescopes use mirrors, avoiding chromatic aberration and allowing large apertures. Cassegrain systems fold the optical path using a concave primary and convex secondary mirror.'],
  ['Resolution and collecting power','A larger aperture collects more radiation and improves the smallest angular separation that can be resolved. Resolution depends on wavelength as well as aperture, so different parts of the electromagnetic spectrum require different telescope designs.'],
  ['Detectors and other wavebands','Radio, infrared, ultraviolet and X-ray astronomy use detectors and locations chosen for the relevant wavelengths and atmospheric transmission. CCDs offer high quantum efficiency, convenient digital processing and repeatable measurement compared with the unaided eye.']
 ],[['Angular magnification','M = fₒ/fₑ','normal adjustment'],['Rayleigh criterion','θ ≈ 1.22λ/D','rad'],['Collecting power','collecting power ∝ D²','']],{q:'An astronomical telescope has objective focal length 1.20 m and eyepiece focal length 25 mm. Find its angular magnification.',steps:['Convert 25 mm to 0.025 m.','Use M = fₒ/fₑ.','M = 1.20/0.025.'],answer:'48'},'Keep resolving power and collecting power separate: aperture affects both, but through different relationships.',['Why do reflecting telescopes avoid chromatic aberration?','How does doubling aperture affect collecting power?','State the Rayleigh relationship for angular resolution.']),
 c('astro-stars','2. Stellar classification and the H–R diagram','Use magnitude, spectra and black-body models to classify stars and infer their physical properties.',[
  ['Magnitude and distance','Apparent magnitude describes how bright a star appears from Earth, while absolute magnitude compares stars at a standard distance of 10 pc. The magnitude scale is logarithmic: a difference of 1 magnitude corresponds to an intensity ratio of about 2.51.'],
  ['Black-body stars','A star can be approximated as a black body. Wien’s law links peak wavelength to surface temperature, while Stefan’s law links luminosity to surface area and the fourth power of temperature. These relationships allow radius, luminosity and temperature to be compared.'],
  ['Spectra and the H–R diagram','Spectral class runs O, B, A, F, G, K, M from hotter to cooler stars. The H–R diagram places luminosity or absolute magnitude against temperature/spectral class and separates the main sequence, giants and white dwarfs.']
 ],[['Distance modulus','m − M = 5 log₁₀(d/10)','d in pc'],['Wien','λmax T = 2.90 × 10⁻³','m K'],['Stefan','L = 4πR²σT⁴','W']],{q:'A star has peak wavelength 500 nm. Estimate its surface temperature.',steps:['Convert 500 nm to 5.00 × 10⁻⁷ m.','Use T = 2.90×10⁻³/λmax.'],answer:'≈ 5.8 × 10³ K'},'Remember that the temperature axis on a conventional H–R diagram decreases from left to right.',['What is absolute magnitude?','How does Wien’s law allow stellar temperature to be estimated?','Where are white dwarfs found on an H–R diagram?']),
 c('astro-evolution','3. Stellar evolution, supernovae and compact objects','Follow the life cycle of stars and use energetic models for supernovae, neutron stars and black holes.',[
  ['Evolution of Sun-like stars','A protostar contracts until fusion supports the star. A Sun-like star spends most of its life on the main sequence, later expands into a red giant and eventually leaves a white dwarf remnant. Its path on the H–R diagram reflects changing temperature and luminosity.'],
  ['Massive stars and supernovae','Massive stars can undergo core collapse and supernova explosions. The remnant may be a neutron star or black hole. Type Ia supernovae have useful standardisable luminosities and can be used as distance indicators.'],
  ['Black holes','A black hole has an event horizon from which escape would require the speed of light. The Schwarzschild radius provides a characteristic radius for a non-rotating black hole. Supermassive black holes are associated with galactic centres and active galaxies.']
 ],[['Escape speed','vₑ = √(2GM/R)','m s⁻¹'],['Schwarzschild radius','Rₛ = 2GM/c²','m']],{q:'Estimate the Schwarzschild radius of a 2.0 × 10³⁰ kg object.',steps:['Use Rₛ = 2GM/c².','Substitute G = 6.67×10⁻¹¹ and c = 3.00×10⁸ m s⁻¹.'],answer:'≈ 3.0 km'},'Do not describe a black hole as “sucking” everything in; outside it, gravity follows the same field laws as for other masses.',['What distinguishes a neutron star from a black hole?','Why are Type Ia supernovae useful in distance measurement?','State the Schwarzschild-radius equation.']),
 c('astro-cosmology','4. Cosmology, redshift and exoplanets','Use spectra, redshift and light curves to infer motion, distance and the large-scale behaviour of the Universe.',[
  ['Doppler shift and redshift','Motion along the line of sight changes the observed wavelength or frequency. For speeds much less than c, fractional wavelength or frequency shift is proportional to radial speed. Binary stars can therefore reveal orbital motion through alternating spectral shifts.'],
  ['Hubble expansion and the Big Bang','Hubble’s law relates recessional speed to distance. Interpreting this as expansion gives an approximate age scale of 1/H₀. Evidence for the Big Bang includes the cosmic microwave background and the observed abundance of light elements.'],
  ['Quasars and exoplanets','Quasars are extremely luminous distant active galactic nuclei powered by accretion around supermassive black holes. Exoplanets can be detected by periodic stellar Doppler shifts or by transit light curves that show repeated reductions in received intensity.']
 ],[['Low-speed Doppler','Δλ/λ ≈ v/c','v ≪ c'],['Hubble law','v = H₀d','']],{q:'A galaxy is 100 Mpc away and H₀ = 70 km s⁻¹ Mpc⁻¹. Estimate its recessional speed.',steps:['Use v = H₀d.','v = 70 × 100 km s⁻¹.'],answer:'7000 km s⁻¹'},'A redshift indicates recession only when the shift is interpreted in the relevant astrophysical context.',['How can a transit reveal an exoplanet?','What does the gradient of a velocity–distance graph represent?','Give two pieces of evidence supporting the Big Bang model.'])
]};

D['medical-physics']={code:'AQA 3.10',title:'Medical physics',year:'Year 13 · Paper 3 option',option:true,chapters:[
 c('med-eye','1. Physics of the eye','Apply geometrical optics to vision and the correction of common refractive defects.',[
  ['The eye as an optical system','The cornea and lens refract light to form an image on the retina. Accommodation changes the effective optical power so that objects at different distances can be focused. Rods and cones differ in sensitivity and spatial resolution.'],
  ['Vision defects and correction','Myopia is corrected using a diverging lens and hypermetropia using a converging lens. Astigmatism requires different optical power in different planes and is described using prescription cylinder and axis information.'],
  ['Lens power','Lens power is measured in dioptres and is the reciprocal of focal length in metres. Ray diagrams should show how the correcting lens changes the rays so the eye can focus them on the retina.']
 ],[['Lens power','P = 1/f','D, f in m']],{q:'A correcting lens has focal length −0.50 m. Calculate its power.',steps:['Use P = 1/f.','P = 1/(−0.50).'],answer:'−2.0 D'},'Keep sign convention consistent: diverging correcting lenses have negative power.',['Which lens corrects myopia?','What is a dioptre?','Why can rods be sensitive but give poorer spatial resolution than cones?']),
 c('med-ear-ecg','2. Hearing and biological measurement','Use wave and logarithmic ideas to interpret hearing, and understand how an ECG records electrical activity.',[
  ['Ear as a detector','The outer and middle ear transfer sound energy to the inner ear, where mechanical motion is converted into electrical signals. Frequency response and sensitivity vary across the audible range.'],
  ['Sound intensity level','Perceived loudness covers a huge intensity range, so sound levels use a logarithmic decibel scale. Equal-loudness curves show that sensitivity depends strongly on frequency as well as intensity.'],
  ['ECG measurement','An ECG measures potential differences associated with the heart’s electrical activity using surface electrodes. The characteristic waveform reflects the sequence of electrical activation through the cardiac cycle.']
 ],[['Intensity','I = P/A','W m⁻²'],['Sound level','β = 10 log₁₀(I/I₀)','dB']],{q:'A sound has intensity 1000 times the reference intensity. Find its level above the reference.',steps:['Use β = 10 log₁₀(I/I₀).','log₁₀(1000)=3.'],answer:'30 dB'},'A decibel value is logarithmic; adding 10 dB multiplies intensity by 10 rather than adding a fixed intensity.',['Why is a logarithmic scale useful for hearing?','What quantity does an ECG record?','How can hearing loss change equal-loudness curves?']),
 c('med-nonionising','3. Ultrasound, endoscopy and MRI','Compare non-ionising imaging systems using wave behaviour, resolution and safety.',[
  ['Ultrasound','Ultrasound pulses reflect at boundaries where acoustic impedance changes. Piezoelectric transducers generate and detect pulses, while pulse timing gives depth information. A-scans display echo amplitude against time and B-scans build a 2D image.'],
  ['Fibre optics and endoscopy','Total internal reflection guides light along fibres. Coherent bundles preserve spatial arrangement for imaging, while non-coherent bundles can deliver illumination. Flexible endoscopes allow internal imaging without large incisions.'],
  ['MRI','In a strong magnetic field, hydrogen nuclei have preferred spin orientations and precess about the field. RF pulses excite selected regions; emitted RF signals during de-excitation are detected and processed to create images. Gradient fields provide spatial selection.']
 ],[['Acoustic impedance','Z = ρc','kg m⁻² s⁻¹'],['Intensity reflection coefficient','R = ((Z₂−Z₁)/(Z₂+Z₁))²',''],['Wave speed','c = fλ','m s⁻¹']],{q:'Why is coupling gel used in ultrasound imaging?',steps:['Air has very different acoustic impedance from tissue.','A large impedance mismatch causes strong reflection.','Gel removes the air gap and improves transmission into the body.'],answer:'It reduces impedance mismatch at the skin boundary.'},'When comparing imaging methods, separate resolution, penetration, safety and convenience rather than giving a single generic advantage.',['What determines reflection at a tissue boundary?','What is the role of piezoelectric material?','Why are gradient coils needed in MRI?']),
 c('med-xray','4. X-rays and CT','Explain X-ray production, attenuation, image formation and computed tomography.',[
  ['X-ray production','Electrons accelerated through a large potential difference strike a target. Their kinetic energy is converted into a continuous X-ray spectrum with characteristic lines superimposed. The maximum photon energy cannot exceed the electron energy eV.'],
  ['Attenuation and contrast','X-ray intensity decreases approximately exponentially with absorber thickness. Different tissues have different attenuation, producing contrast. Contrast agents can increase absorption in selected structures.'],
  ['CT imaging','A CT scanner records many X-ray projections from different directions using a narrow beam and detector array. A computer reconstructs cross-sectional images, trading higher structural information against greater complexity and ionising-radiation exposure.']
 ],[['Maximum photon energy','Emax = eV','J'],['Attenuation','I = I₀e⁻ᵘˣ',''],['Half-value thickness','x½ = ln2/μ','m']],{q:'An X-ray beam has μ = 0.50 cm⁻¹. Find the half-value thickness.',steps:['Use x½ = ln2/μ.','x½ = 0.693/0.50.'],answer:'1.39 cm'},'For medical imaging comparisons, state both image-quality and safety consequences.',['How does accelerating voltage affect maximum X-ray photon energy?','Define half-value thickness.','Why does CT provide cross-sectional information?']),
 c('med-nuclear','5. Radionuclide imaging and therapy','Understand tracer imaging, half-lives, gamma cameras and the physical basis of radiotherapy.',[
  ['Tracer imaging','A gamma-emitting tracer can be attached to a compound that concentrates in a target organ. A useful radionuclide balances detectable photon energy, suitable chemistry and a half-life long enough for imaging but not unnecessarily long. PET uses positron-emitting tracers and coincidence detection of annihilation photons.'],
  ['Half-lives','Physical half-life describes nuclear decay, biological half-life describes removal from the body, and effective half-life combines both processes. Faster removal by either mechanism shortens the effective half-life.'],
  ['Gamma cameras and treatment','Gamma cameras use collimation, scintillation and photomultiplier detection to locate gamma emission. High-energy X-rays can be directed externally for therapy, while selected radioactive sources can be placed internally; treatment planning aims to maximise tumour dose while limiting healthy-tissue exposure.']
 ],[['Effective half-life','1/Tₑ = 1/Tₚ + 1/Tᵦ',''],['Activity','A = λN','Bq']],{q:'A tracer has physical half-life 6 h and biological half-life 12 h. Find effective half-life.',steps:['Use 1/Te = 1/Tp + 1/Tb.','1/Te = 1/6 + 1/12 = 1/4.'],answer:'4 h'},'Do not choose a medical isotope from half-life alone; radiation type, photon energy and biochemical targeting also matter.',['Distinguish physical and biological half-life.','Why is collimation needed in a gamma camera?','Why is technetium-99m widely useful for imaging?'])
]};

D['engineering-physics']={code:'AQA 3.11',title:'Engineering physics',year:'Year 13 · Paper 3 option',option:true,chapters:[
 c('eng-rotation','1. Rotational dynamics','Extend mechanics from linear motion to rotating systems using moment of inertia, torque and angular momentum.',[
  ['Moment of inertia','Moment of inertia measures resistance to angular acceleration and depends on both mass and how far that mass lies from the axis. Moving mass outward increases I strongly because distance enters squared for point masses.'],
  ['Rotational energy and motion','Rotational kinetic energy depends on I and angular speed. Angular displacement, velocity and acceleration have direct analogies with displacement, velocity and acceleration in linear motion, allowing constant-angular-acceleration equations to be used.'],
  ['Torque, momentum and power','Resultant torque produces angular acceleration. Angular momentum is conserved when external torque is negligible. Work done by a constant torque depends on angular displacement, and rotational power depends on torque and angular speed.']
 ],[['Moment of inertia','I = Σmr²','kg m²'],['Rotational KE','E = ½Iω²','J'],['Torque','τ = Iα','N m'],['Angular momentum','L = Iω','kg m² s⁻¹'],['Rotational power','P = τω','W']],{q:'A flywheel has I = 4.0 kg m² and ω = 20 rad s⁻¹. Calculate its rotational kinetic energy.',steps:['Use E = ½Iω².','E = 0.5 × 4.0 × 20².'],answer:'800 J'},'Do not substitute mass for moment of inertia: geometry matters in rotational dynamics.',['Why does moving mass away from the axis increase I?','State the condition for angular momentum conservation.','Write the rotational analogue of F = ma.']),
 c('eng-thermo','2. Thermodynamic processes and p–V diagrams','Apply the first law to idealised gas processes and interpret work from pressure–volume graphs.',[
  ['First law','Energy transferred by heating can increase internal energy or be transferred out as work done by the system. A consistent sign convention is essential when applying the first law.'],
  ['Idealised processes','Isothermal processes occur at constant temperature, adiabatic processes involve no energy transfer by heating, isobaric processes occur at constant pressure, and isochoric processes at constant volume. Each constrains the first-law terms differently.'],
  ['p–V diagrams','For a quasi-static process, area under a p–V curve represents work done by the gas. For a complete cycle, the enclosed area represents net work done per cycle.']
 ],[['First law','Q = ΔU + W','W done by system'],['Isothermal ideal gas','pV = constant',''],['Adiabatic ideal gas','pVᵞ = constant',''],['Constant pressure work','W = pΔV','J']],{q:'A gas expands at constant pressure 2.0×10⁵ Pa by 3.0×10⁻³ m³. Find the work done.',steps:['Use W = pΔV.','W = 2.0×10⁵ × 3.0×10⁻³.'],answer:'600 J'},'On a cyclic p–V graph, the enclosed area is net work, not the area under one individual process alone.',['What is zero in an adiabatic process?','How is work represented on a p–V diagram?','State the first law using work done by the system.']),
 c('eng-engines','3. Engines, efficiency and reversed heat engines','Analyse heat-engine cycles, practical efficiency and the second-law need for a cold sink.',[
  ['Engine cycles','Indicator diagrams represent pressure–volume changes over engine cycles. The loop area gives work per cycle, which combines with cycle frequency and cylinder number to estimate indicated power.'],
  ['Efficiency and the second law','No heat engine can convert all supplied thermal energy into useful work because energy must also be transferred to a colder sink. Maximum theoretical efficiency depends only on absolute source and sink temperatures.'],
  ['Refrigerators and heat pumps','Reversed heat engines use work input to transfer energy from a colder region to a warmer region. Their performance is described by a coefficient of performance rather than a heat-engine efficiency.']
 ],[['Heat-engine efficiency','η = W/QH',''],['Maximum efficiency','ηmax = (TH−TC)/TH','temperatures in K'],['Refrigerator COP','COP = QC/W',''],['Heat-pump COP','COP = QH/W','']],{q:'An ideal engine operates between 600 K and 300 K. Find its maximum theoretical efficiency.',steps:['Use ηmax = (TH−TC)/TH.','η = (600−300)/600.'],answer:'0.50 or 50%'},'Temperature in Carnot-style efficiency equations must be in kelvin.',['Why must a heat engine have a sink?','What does the area of an indicator loop represent?','Distinguish efficiency from coefficient of performance.'])
]};

D['turning-points']={code:'AQA 3.12',title:'Turning points in physics',year:'Year 13 · Paper 3 option',option:true,chapters:[
 c('tp-electron','1. Discovery of the electron','Understand the experiments that established electrons as charged particles with quantised charge.',[
  ['Cathode rays and thermionic emission','Discharge tubes produced cathode rays that could be deflected by electric and magnetic fields. Thermionic emission provided a controllable source of electrons by releasing electrons from a heated metal surface.'],
  ['Specific charge','Thomson-style experiments measured the charge-to-mass ratio e/m, showing cathode-ray particles had a much larger specific charge than hydrogen ions and were therefore a new subatomic constituent.'],
  ['Millikan and charge quantisation','Oil-drop measurements balanced electric and gravitational forces and used terminal motion to infer droplet charge. Repeated results showed charge occurred in integer multiples of a fundamental value e.']
 ],[['Electron energy','eV = ½mv²','non-relativistic'],['Magnetic orbit','evB = mv²/r',''],['Stokes drag','F = 6πηrv','']],{q:'An electron accelerated through 500 V gains how much kinetic energy in eV?',steps:['Energy gained by charge e through 1 V is 1 eV.','Through 500 V, energy gain is 500 eV.'],answer:'500 eV'},'The importance of Thomson and Millikan is conceptual as well as numerical: together they established charge-to-mass ratio and quantised charge.',['What did the large e/m ratio imply?','What force balance holds for a stationary charged oil drop?','What did Millikan’s results show about charge?']),
 c('tp-duality','2. Wave–particle duality','Trace the historical shift from competing wave/particle models to quantum duality.',[
  ['Competing theories of light','Newton’s corpuscular model initially had strong authority, while Huygens described wave propagation. Young’s double-slit observations gave decisive interference evidence for a wave description.'],
  ['Electromagnetism and quanta','Maxwell’s theory unified electric and magnetic fields into electromagnetic waves and predicted their propagation speed. Black-body radiation and the photoelectric effect later required quantised energy ideas, leading to the photon model.'],
  ['Matter waves and microscopes','de Broglie proposed wavelength λ = h/p for matter. Electron diffraction confirmed wave behaviour. Electron microscopes exploit very short electron wavelengths to achieve resolution beyond conventional light microscopes.']
 ],[['EM-wave speed','c = 1/√(μ₀ε₀)','m s⁻¹'],['Photon energy','E = hf','J'],['de Broglie','λ = h/p','m']],{q:'What happens to an electron’s de Broglie wavelength if its momentum doubles?',steps:['Use λ = h/p.','λ is inversely proportional to p.'],answer:'It halves.'},'Historical experiments should be linked to the model they challenged or supported, not learned as isolated stories.',['Why was Young’s experiment significant?','What did Maxwell’s theory predict?','Why can electron microscopes resolve smaller structures than optical microscopes?']),
 c('tp-relativity','3. Special relativity','Use Einstein’s postulates to understand time dilation, length contraction and relativistic energy.',[
  ['Michelson–Morley and invariance','The Michelson–Morley experiment failed to detect motion through a luminiferous ether. This supported abandoning absolute-motion models and is consistent with the invariance of the speed of light.'],
  ['Einstein’s postulates','The laws of physics have the same form in all inertial frames, and the speed of light in vacuum is the same for every inertial observer. These postulates require new relationships between space and time.'],
  ['Time, length and energy','Proper time is measured in the frame where the events occur at the same position; moving clocks are observed to run slow. Proper length is measured in the object’s rest frame; moving lengths contract along the direction of motion. Relativistic effects become large as v approaches c.']
 ],[['Lorentz factor','γ = 1/√(1−v²/c²)',''],['Time dilation','t = γt₀','s'],['Length contraction','L = L₀/γ','m'],['Mass-energy','E = mc²','J']],{q:'A spacecraft moves at 0.80c. Calculate γ.',steps:['γ = 1/√(1−0.80²).','1−0.64 = 0.36; √0.36 = 0.60.'],answer:'1.67'},'Always identify which quantity is proper before applying time-dilation or length-contraction equations.',['State Einstein’s two postulates.','What is proper time?','Why do relativistic effects become important near c?'])
]};

D.electronics={code:'AQA 3.13',title:'Electronics',year:'Year 13 · Paper 3 option',option:true,chapters:[
 c('el-devices','1. Semiconductor devices and sensors','Use characteristic curves and functional models for MOSFETs, Zener diodes, photodiodes and Hall sensors.',[
  ['MOSFET','An n-channel enhancement MOSFET uses gate-source voltage to control drain current. Its gate has very high input resistance, allowing it to act as an electronically controlled switch with little input current.'],
  ['Zener and photodiodes','A Zener diode operated in reverse breakdown can provide a reference voltage when used with a suitable series resistor. A reverse-biased photodiode produces a response dependent on incident light and can act as an optical detector.'],
  ['Hall sensors','Hall-effect sensors provide an electrical output related to magnetic field and can be used for position, orientation or rotational-speed sensing. Detailed internal operation is not required for this option.']
 ],[],{q:'Why is a MOSFET useful as an electronic switch at a sensor output?',steps:['Its gate has very high input resistance.','Very little input current is needed.','A gate voltage can control a much larger drain current.'],answer:'Voltage control with very high input resistance.'},'Use the characteristic curve and named terminals rather than describing semiconductor devices only as “on” or “off”.',['Name the MOSFET terminals.','What is Zener breakdown used for?','Give one use of a Hall sensor.']),
 c('el-signals','2. Analogue and digital signals','Understand sampling, quantisation and the benefits and limitations of digital representation.',[
  ['Analogue versus digital','Analogue signals vary continuously; digital signals use discrete levels. Sampling records signal values at regular intervals, while quantisation maps those values to a finite set of digital levels.'],
  ['Sampling quality','Higher sampling rate records faster variation more faithfully, while more bits per sample increase the number of amplitude levels and reduce quantisation error. Both increase the data rate.'],
  ['Noise and recovery','Digital transmission can regenerate recognised logic levels and prevent small noise contributions accumulating in the same way as analogue distortion. Severe noise can still produce incorrect bit decisions.']
 ],[['Bit rate','bit rate = samples s⁻¹ × bits sample⁻¹','bit s⁻¹']],{q:'Audio is sampled at 40 kHz using 16 bits per sample. Find the raw mono bit rate.',steps:['40 kHz = 40,000 samples s⁻¹.','Multiply by 16 bits.'],answer:'640,000 bit s⁻¹'},'Higher sample rate and bit depth improve representation but also increase storage and transmission requirements.',['What is quantisation?','How does bit depth affect quality?','Why can digital signals be regenerated after noise?']),
 c('el-analogue','3. LC filters and operational amplifiers','Use resonance and ideal op-amp assumptions to process analogue signals.',[
  ['LC resonance filters','A parallel LC circuit has a resonant frequency set by inductance and capacitance. Its response can select a narrow frequency range; Q factor compares resonant frequency with bandwidth.'],
  ['Ideal op-amp','An ideal operational amplifier has extremely large open-loop gain and input resistance. In open-loop use it acts as a comparator; with negative feedback it becomes a predictable amplifier building block.'],
  ['Real limitations','Real devices have finite gain and bandwidth. Frequency-response graphs show how closed-loop behaviour eventually departs from the low-frequency gain.']
 ],[['LC resonance','f₀ = 1/(2π√(LC))','Hz'],['Q factor','Q = f₀/fB','']],{q:'An LC filter has f₀ = 10 kHz and bandwidth 500 Hz. Find Q.',steps:['Use Q=f₀/fB.','10,000/500 = 20.'],answer:'20'},'Do not confuse resonance frequency with bandwidth; Q compares them.',['What determines LC resonance frequency?','What ideal op-amp property makes input current negligible?','What does a larger Q imply about bandwidth?']),
 c('el-opamps','4. Op-amp circuits','Analyse inverting, non-inverting, summing and difference amplifier configurations.',[
  ['Inverting amplifier','Negative feedback holds the inverting input close to the non-inverting input potential. With the non-inverting input grounded this creates a virtual earth, allowing current balance to produce a precise negative voltage gain.'],
  ['Non-inverting amplifier','A non-inverting arrangement produces positive gain greater than or equal to 1, with high input resistance at the signal input.'],
  ['Summing and difference circuits','Summing amplifiers combine weighted input voltages. Difference amplifiers respond to the difference between two inputs and are useful where common signals or offsets need to be rejected.']
 ],[['Inverting gain','Vout/Vin = −Rf/Rin',''],['Non-inverting gain','Vout/Vin = 1 + Rf/R1','']],{q:'An inverting amplifier has Rin = 10 kΩ and Rf = 100 kΩ. Find the voltage gain.',steps:['Use gain = −Rf/Rin.','−100/10 = −10.'],answer:'−10'},'The minus sign in an inverting amplifier represents phase inversion, not a negative magnitude of amplification.',['What is meant by virtual earth?','State the inverting-gain equation.','Why is negative feedback useful?']),
 c('el-digital','5. Logic, counters and astables','Build digital functions from logic gates and interpret common sequential circuits.',[
  ['Combinational logic','AND, NAND, OR, NOR, NOT and EOR gates can be combined to implement Boolean functions. Truth tables provide a systematic route from required behaviour to logic expressions and circuit designs.'],
  ['Sequential logic and counters','Sequential circuits depend on previous state as well as present inputs. Binary, BCD and Johnson counters respond to clock pulses and may include reset and up/down control. Modulo-n behaviour can be produced by resetting at a chosen count.'],
  ['Astables','An astable is a free-running oscillator that produces clock pulses. Important descriptions include frequency, period, pulse width, duty cycle and mark-to-space ratio.']
 ],[['Frequency and period','f = 1/T','Hz'],['Duty cycle','duty cycle = pulse width / period × 100%','%']],{q:'A clock pulse is high for 2 ms in a 5 ms period. Find duty cycle.',steps:['Use high time/period ×100%.','2/5 ×100%.'],answer:'40%'},'You need to interpret logic and counter behaviour, not reproduce the internal transistor circuits of gates.',['What distinguishes combinational from sequential logic?','What does reset do in a counter?','Define duty cycle.']),
 c('el-comms','6. Data communication systems','Describe communication-system blocks, transmission media, multiplexing and modulation.',[
  ['Communication chain','A real-time communication system can be represented by input transducer, signal processing/encoding, transmitter, channel, receiver/decoding and output transducer. Each stage has a clear functional role.'],
  ['Transmission media and multiplexing','Metal cable, optical fibre and electromagnetic links differ in bandwidth, attenuation, cost and security. Time-division multiplexing lets several data streams share a channel by allocating repeating time slots.'],
  ['AM and FM','Modulation places information onto a higher-frequency carrier. In amplitude modulation the carrier amplitude varies; in frequency modulation its instantaneous frequency varies. Bandwidth and noise behaviour differ between methods and transmission media.']
 ],[['Simple AM bandwidth','bandwidth ≈ 2fm','Hz'],['FM bandwidth estimate','bandwidth ≈ 2(Δf + fm)','Hz']],{q:'An AM signal carries a highest information frequency of 5 kHz. Estimate the simple AM bandwidth.',steps:['Use bandwidth ≈ 2fm.','2 × 5 kHz.'],answer:'10 kHz'},'Carrier frequency and information frequency play different roles; identify them separately from a time-domain waveform.',['What is the purpose of modulation?','What does time-division multiplexing do?','Give one advantage of optical fibre over metal wire.'])
]};

// Make option topics available in the textbook topic selector even though they are not core CourseApp modules.
const OPTION_IDS=['astrophysics','medical-physics','engineering-physics','turning-points','electronics'];
function addOptionSelectors(){
 const selects=[document.getElementById('textbookTopicSelect')].filter(Boolean);
 selects.forEach(select=>{
   const marker=[...select.options].find(o=>o.dataset?.paper3==='1');
   if(marker)return;
   const group=document.createElement('optgroup');group.label='Paper 3 options';
   OPTION_IDS.forEach(id=>{const t=D[id];if(!t)return;const o=document.createElement('option');o.value=id;o.textContent=`${t.code} · ${t.title}`;o.dataset.paper3='1';group.appendChild(o)});
   select.appendChild(group);
   const s=window.CourseTextbook?.getState?.();if(s?.topicId&&OPTION_IDS.includes(s.topicId))select.value=s.topicId;
 });
}
window.addEventListener('textbookchange',()=>setTimeout(addOptionSelectors,30));
const start=()=>{addOptionSelectors();if(!document.getElementById('textbookTopicSelect'))setTimeout(start,160)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.ALEVEL_PAPER3_OPTIONS={ids:OPTION_IDS,data:OPTION_IDS.map(id=>D[id])};
})();