(()=>{
  'use strict';
  const data=window.PhysicsTextbookData||{};
  const topicOrder=(window.CourseApp?.topics||[]).map(t=>t.id).filter(id=>data[id]);
  const locationKey='alevel-physics-textbook-location-v1';
  const readKey='alevel-physics-textbook-read-v1';
  let savedLocation=safeJson(localStorage.getItem(locationKey),{});
  const readState=safeJson(localStorage.getItem(readKey),{});
  let activeTopic=savedLocation.topic&&data[savedLocation.topic]?savedLocation.topic:(topicOrder[0]||Object.keys(data)[0]);
  let activeChapter=Number(savedLocation.chapter)||0;
  let lastTrigger=null;
  let toastTimer=null;

  const TERM_INFO={
    'accuracy':{d:'How close a measured value is to the accepted or true value.',more:'Accuracy is mainly limited by systematic effects, calibration and the quality of the method. A set of readings can be very precise but still inaccurate.',exam:'When evaluating data, distinguish accuracy from precision rather than using the words interchangeably.'},
    'precision':{d:'How closely repeated measurements agree with one another.',more:'Precision is linked to the spread of repeated values and the resolution of the measuring instrument. Repeats can improve confidence in a mean but do not remove a systematic offset.',exam:'Small scatter indicates good precision, not necessarily good accuracy.'},
    'uncertainty':{d:'An estimate of the range around a measured value within which the true value is reasonably expected to lie.',more:'Uncertainty can be quoted as an absolute value or as a percentage. In calculated quantities, the way uncertainties combine depends on whether values are added, multiplied or raised to powers.',exam:'Quote an uncertainty with sensible significant figures and match the decimal place of the measured value.'},
    'systematic error':{d:'An error that shifts measurements consistently in the same direction.',more:'Examples include zero error, poor calibration and a repeated heat-loss effect. Repeating readings does not remove a systematic error.',exam:'Suggest a change to apparatus or calibration when asked how to reduce systematic error.'},
    'random error':{d:'An unpredictable variation that makes repeated readings scatter around a central value.',more:'Random error can arise from judgement, timing variation or fluctuating conditions. Repeated measurements and averaging reduce its influence on the mean.',exam:'Use spread or repeat readings as evidence when discussing random uncertainty.'},
    'resolution':{d:'The smallest change in a quantity that an instrument can display or distinguish.',more:'Resolution places a lower limit on how finely a reading can be reported. It is not the same as accuracy.',exam:'Relate the quoted reading uncertainty to the instrument scale or digital step.'},
    'gradient':{d:'The change in the vertical-axis quantity divided by the change in the horizontal-axis quantity.',more:'A graph gradient often represents a physical constant or combination of constants. Its units are the y-axis units divided by the x-axis units.',exam:'Use a large triangle drawn on the best-fit line, not two raw data points.'},
    'photon':{d:'A quantum of electromagnetic radiation carrying energy E = hf.',more:'Photons also carry momentum p = h/λ. Their energy depends on frequency rather than intensity.',equation:'E = hf = hc/λ',exam:'Higher intensity means more photons per second; higher frequency means more energy per photon.'},
    'work function':{d:'The minimum energy needed to remove an electron from the surface of a material.',more:'The work function φ sets the threshold frequency f₀ through φ = hf₀. Energy above the work function can appear as electron kinetic energy.',equation:'hf = φ + Eₖ,max',exam:'Do not say intensity changes the maximum kinetic energy when frequency is fixed.'},
    'threshold frequency':{d:'The minimum frequency of incident radiation that can produce photoelectrons from a surface.',more:'Below the threshold frequency, individual photons do not carry enough energy to overcome the work function, regardless of intensity.',equation:'φ = hf₀',exam:'Use the one-photon/one-electron model when explaining the threshold.'},
    'de broglie wavelength':{d:'The wavelength associated with a particle of momentum p.',more:'Matter-wave effects become observable when this wavelength is comparable with structures such as crystal lattice spacings.',equation:'λ = h/p',exam:'Increasing momentum decreases the de Broglie wavelength.'},
    'baryon':{d:'A hadron made from three quarks.',more:'Protons and neutrons are baryons. Baryon number is conserved in the A-level particle interactions considered.',exam:'Distinguish baryons from mesons, which contain a quark–antiquark pair.'},
    'meson':{d:'A hadron made from a quark and an antiquark.',more:'Mesons have baryon number zero and participate in the strong interaction because they are hadrons.',exam:'Use quark composition to check charge and particle classification.'},
    'lepton':{d:'A fundamental particle that does not experience the strong interaction.',more:'Electrons and neutrinos are leptons. Lepton number is conserved in the interactions studied at A level.',exam:'Neutrinos are leptons even though they have no electric charge.'},
    'quark':{d:'A fundamental particle that combines to form hadrons.',more:'For the core course, up, down and strange quarks are especially important. Up carries +2/3 e; down and strange carry −1/3 e.',exam:'Write fractional quark charges carefully when checking proton, neutron or meson charge.'},
    'annihilation':{d:'A process in which a particle and its antiparticle convert their rest energy and kinetic energy into other particles, often photons.',more:'Energy and momentum must both be conserved. Electron–positron annihilation commonly produces two photons so momentum can be conserved.',exam:'Use total initial energy, including rest energy, when calculating photon energy.'},
    'pair production':{d:'Creation of a particle–antiparticle pair from a photon with sufficient energy.',more:'A nearby nucleus is normally needed to allow momentum to be conserved. The photon energy must at least equal the total rest energy created.',exam:'Check the threshold energy before considering kinetic energy.'},
    'amplitude':{d:'The maximum displacement of an oscillating point from its equilibrium position.',more:'Amplitude is not the same as wavelength. For many waves, greater amplitude corresponds to greater energy transfer.',exam:'Read amplitude vertically from the equilibrium line, not peak-to-trough.'},
    'wavelength':{d:'The shortest distance between two points on a wave that are in the same phase.',more:'Examples include crest-to-crest or compression-to-compression. It is linked to speed and frequency by v = fλ.',equation:'v = fλ',exam:'Use SI metres before substituting unless units are otherwise consistent.'},
    'frequency':{d:'The number of complete oscillations or cycles per second.',more:'Frequency is measured in hertz and is the reciprocal of period.',unit:'Hz',equation:'f = 1/T',exam:'Frequency is set by the source and normally stays constant when a wave crosses a boundary.'},
    'phase difference':{d:'A measure of how far through a cycle one oscillation is relative to another.',more:'Phase difference can be expressed in degrees, radians or as a fraction of a cycle. Half a wavelength corresponds to π radians or 180°.',equation:'Δφ = 2πΔx/λ',exam:'State whether waves arrive in phase or antiphase when explaining interference.'},
    'superposition':{d:'The principle that overlapping waves combine by adding their instantaneous displacements.',more:'Superposition produces interference and stationary-wave patterns.',exam:'Resultant displacement is the algebraic/vector sum of the individual displacements.'},
    'node':{d:'A point on a stationary wave that has zero amplitude.',more:'Adjacent nodes are separated by half a wavelength. A fixed end of a string is a node.',exam:'Do not describe a node as a point where the wave has permanently zero displacement in a travelling wave.'},
    'antinode':{d:'A point on a stationary wave where the oscillation amplitude is maximum.',more:'Antinodes lie midway between adjacent nodes in an ideal stationary wave.',exam:'Adjacent antinodes are separated by λ/2; a node and nearest antinode by λ/4.'},
    'coherence':{d:'A condition in which sources have the same frequency and a constant phase difference.',more:'Coherent sources are needed for a stable interference pattern.',exam:'Two slits illuminated by the same source are a standard method of producing coherent waves.'},
    'diffraction':{d:'The spreading of waves when they pass through a gap or around an obstacle.',more:'Diffraction is strongest when the gap size is comparable with the wavelength. Longer wavelengths diffract more for the same aperture.',exam:'A narrower aperture produces a wider diffraction pattern when wavelength is fixed.'},
    'refractive index':{d:'A measure of how much light slows in a material compared with vacuum.',more:'Refractive index also relates incidence and refraction angles through Snell’s law.',equation:'n = c/v',exam:'Angles are measured from the normal, not from the surface.'},
    'critical angle':{d:'The angle of incidence in the denser medium that gives an angle of refraction of 90°.',more:'For angles larger than the critical angle, total internal reflection occurs if the wave is travelling from higher to lower refractive index.',equation:'sin c = n₂/n₁',exam:'State both conditions for total internal reflection.'},
    'displacement':{d:'Change in position in a specified direction from a reference point.',more:'Displacement is a vector quantity and is different from distance travelled.',unit:'m',exam:'Include direction or sign when a question requires a vector result.'},
    'velocity':{d:'Rate of change of displacement.',more:'Velocity is a vector; speed is its magnitude. On a displacement–time graph, gradient gives velocity.',unit:'m s⁻¹',equation:'v = Δs/Δt',exam:'Use signs consistently when motion reverses direction.'},
    'acceleration':{d:'Rate of change of velocity.',more:'Acceleration can occur when speed changes, direction changes, or both.',unit:'m s⁻²',equation:'a = Δv/Δt',exam:'In circular motion an object can accelerate at constant speed because its velocity direction changes.'},
    'resultant force':{d:'The vector sum of all forces acting on an object.',more:'The resultant force determines acceleration through Newton’s second law.',unit:'N',equation:'F = ma',exam:'Draw and combine forces before substituting into F = ma.'},
    'momentum':{d:'The product of mass and velocity; a vector measure of motion.',more:'Total momentum of a closed system is conserved. Impulse equals change in momentum.',unit:'kg m s⁻¹',equation:'p = mv',exam:'Choose a positive direction before applying momentum conservation.'},
    'impulse':{d:'The change in momentum caused by a force acting over a time interval.',more:'Impulse is equal to the area under a force–time graph.',unit:'N s',equation:'J = FΔt = Δp',exam:'For a varying force, use the area under the graph rather than simply FΔt with a peak force.'},
    'work':{d:'Energy transferred when a force causes displacement.',more:'For a constant force, only the component of force in the displacement direction does work.',unit:'J',equation:'W = Fs cosθ',exam:'Check the angle is between the force and displacement vectors.'},
    'power':{d:'Rate of energy transfer or rate of doing work.',unit:'W',equation:'P = E/t = Fv (for force parallel to velocity)',more:'Power describes how quickly energy is transferred, not how much energy is transferred in total.',exam:'Use watts = joules per second.'},
    'stress':{d:'Force per unit cross-sectional area in a material.',unit:'Pa',equation:'σ = F/A',more:'Stress uses the original cross-sectional area for the standard A-level treatment.',exam:'Convert mm² to m² carefully.'},
    'strain':{d:'Fractional change in length of a material.',equation:'ε = ΔL/L',more:'Strain has no unit because it is a ratio of two lengths.',exam:'Do not attach metres to strain.'},
    'young modulus':{d:'The ratio of tensile stress to tensile strain in the linear elastic region.',unit:'Pa',equation:'E = σ/ε',more:'A larger Young modulus means a stiffer material.',exam:'Use the gradient of the initial straight section of a stress–strain graph.'},
    'elastic limit':{d:'The greatest stress or deformation for which a material returns to its original dimensions when the force is removed.',more:'Beyond the elastic limit, permanent deformation remains.',exam:'Do not confuse elastic limit with the limit of proportionality.'},
    'electric current':{d:'Rate of flow of electric charge.',unit:'A',equation:'I = Q/t',more:'Conventional current is defined in the direction positive charge would move.',exam:'Use charge in coulombs and time in seconds.'},
    'potential difference':{d:'Energy transferred per unit charge between two points.',unit:'V',equation:'V = W/Q',more:'A volt is a joule per coulomb.',exam:'Potential difference is measured across a component, not “through” it.'},
    'emf':{d:'Energy supplied by a source per unit charge passing through it.',unit:'V',equation:'ε = W/Q',more:'Terminal potential difference can be less than emf when current flows because energy is dissipated in internal resistance.',exam:'Distinguish emf from terminal p.d. when internal resistance is involved.'},
    'resistance':{d:'The ratio of potential difference across a component to current through it.',unit:'Ω',equation:'R = V/I',more:'Resistance can depend on temperature and component type; only ohmic conductors have constant resistance under constant physical conditions.',exam:'Do not assume V ∝ I unless the component is ohmic and conditions are constant.'},
    'resistivity':{d:'A material property relating resistance to conductor length and cross-sectional area.',unit:'Ω m',equation:'R = ρL/A',more:'Resistivity is independent of a sample’s dimensions but can depend on temperature.',exam:'Convert area to m² before using the equation.'},
    'internal resistance':{d:'Resistance inside a source that causes a drop in terminal potential difference when current flows.',unit:'Ω',equation:'ε = V + Ir',more:'The lost volts Ir correspond to energy dissipated inside the source per unit charge.',exam:'A V–I graph for a source has intercept ε and gradient −r.'},
    'kirchhoff first law':{d:'At a junction, total current entering equals total current leaving.',more:'This is a consequence of charge conservation.',exam:'Assign current directions consistently before writing the equation.'},
    'kirchhoff second law':{d:'Around a closed loop, the sum of emfs equals the sum of potential drops.',more:'This is a consequence of energy conservation.',exam:'Use a consistent sign convention around the loop.'},
    'capacitance':{d:'Charge stored per unit potential difference across a capacitor.',unit:'F',equation:'C = Q/V',more:'Capacitance depends on geometry and dielectric material, not on the amount of charge currently stored for an ideal capacitor.',exam:'A farad is a coulomb per volt.'},
    'time constant':{d:'The characteristic time RC for charging or discharging a capacitor through a resistor.',unit:'s',equation:'τ = RC',more:'After one time constant during discharge, charge and voltage fall to 1/e of their initial values.',exam:'Use exponential relationships rather than assuming a constant rate of discharge.'},
    'centripetal acceleration':{d:'Acceleration directed toward the centre of a circular path.',unit:'m s⁻²',equation:'a = v²/r = ω²r',more:'It changes the direction of velocity even when speed is constant.',exam:'Centripetal is a direction of resultant force/acceleration, not an extra physical force.'},
    'angular velocity':{d:'Rate of change of angular displacement.',unit:'rad s⁻¹',equation:'ω = 2πf',more:'For uniform circular motion it links linear speed and radius through v = ωr.',exam:'Use radians in angular equations.'},
    'simple harmonic motion':{d:'Oscillation in which acceleration is proportional to displacement from equilibrium and directed toward equilibrium.',equation:'a = −ω²x',more:'The negative sign represents the restoring direction. Velocity is greatest at equilibrium; acceleration magnitude is greatest at the extremes.',exam:'State both proportionality and opposite direction when defining SHM.'},
    'resonance':{d:'A large-amplitude response when a system is driven near its natural frequency.',more:'Energy transfer from the driver is most effective near the natural frequency. Damping reduces the maximum amplitude and broadens the resonance curve.',exam:'Link resonance to driving frequency and natural frequency.'},
    'internal energy':{d:'The total microscopic kinetic and potential energy of particles in a system.',more:'Heating and work can change internal energy. Temperature is linked to the statistical kinetic energy of particles, not total internal energy alone.',exam:'Do not define internal energy simply as “heat stored”.'},
    'specific heat capacity':{d:'Energy required to raise the temperature of 1 kg of a substance by 1 K.',unit:'J kg⁻¹ K⁻¹',equation:'Q = mcΔT',more:'It is a material property over the relevant temperature range.',exam:'Use temperature change, not final temperature, in Q = mcΔT.'},
    'ideal gas':{d:'A model gas whose particles have negligible volume and only elastic collisions, with no intermolecular forces except during collisions.',more:'The ideal gas equation connects macroscopic pressure, volume and temperature with amount of substance.',equation:'pV = nRT = NkT',exam:'Temperature must be in kelvin.'},
    'electric field strength':{d:'Force per unit positive test charge at a point.',unit:'N C⁻¹',equation:'E = F/Q',more:'For a radial field around a point charge, E = Q/(4πε₀r²).',exam:'Field direction is the direction of force on a positive test charge.'},
    'gravitational field strength':{d:'Force per unit mass at a point in a gravitational field.',unit:'N kg⁻¹',equation:'g = F/m',more:'Around a point or spherical mass, g = GM/r² directed inward.',exam:'Do not confuse gravitational field strength g with gravitational potential.'},
    'electric potential':{d:'Electric potential energy per unit positive charge relative to a chosen zero.',unit:'V',equation:'V = W/Q',more:'For a point charge, V = Q/(4πε₀r). Potential is a scalar.',exam:'Potential can be negative around a negative charge.'},
    'gravitational potential':{d:'Gravitational potential energy per unit mass relative to zero at infinity.',unit:'J kg⁻¹',equation:'V = −GM/r',more:'Gravitational potential is negative because work must be done to remove a mass from an attractive field to infinity.',exam:'Potential is scalar; field strength is vector.'},
    'magnetic flux density':{d:'A measure of magnetic field strength defined through the force on current or moving charge.',unit:'T',equation:'F = BIL sinθ',more:'One tesla gives a force of 1 N on 1 m of wire carrying 1 A at right angles to the field.',exam:'Use the component perpendicular to the field.'},
    'magnetic flux':{d:'The product of magnetic flux density and area normal to the field.',unit:'Wb',equation:'Φ = BA cosθ',more:'Flux linkage for a coil is NΦ.',exam:'The angle is between B and the normal to the area.'},
    'faraday law':{d:'The induced emf equals the rate of change of magnetic flux linkage.',equation:'ε = −d(NΦ)/dt',more:'The minus sign represents Lenz’s law: the induced effect opposes the change producing it.',exam:'Increase induced emf by increasing turns or rate of change of flux linkage.'},
    'rutherford scattering':{d:'Scattering of alpha particles by thin metal foil used to infer a small, dense, positively charged nucleus.',more:'Most alpha particles pass through with little deflection because atoms are mostly empty space; rare large-angle scattering implies concentrated positive charge and mass.',exam:'Link each observation to a specific conclusion about atomic structure.'},
    'activity':{d:'The rate at which unstable nuclei decay.',unit:'Bq',equation:'A = λN',more:'One becquerel is one decay per second. Activity decreases exponentially for a single radioactive isotope.',exam:'Activity is not the same as count rate measured by a detector.'},
    'decay constant':{d:'The probability per unit time that a particular unstable nucleus decays.',unit:'s⁻¹',equation:'A = λN',more:'A larger decay constant corresponds to a shorter half-life.',exam:'Use λ = ln2 / T½.'},
    'half-life':{d:'The time for the number of undecayed nuclei, or the activity, to fall to half its value.',unit:'s',equation:'T½ = ln2/λ',more:'Half-life is constant for a given isotope and does not depend on how many nuclei are present.',exam:'Repeated halving is often faster than using the exponential equation for exact half-life intervals.'},
    'binding energy':{d:'The energy required to separate a nucleus completely into its individual nucleons.',unit:'J or eV',equation:'E = Δmc²',more:'Binding energy arises from the mass defect between the nucleus and separated nucleons.',exam:'Binding energy per nucleon is used to compare nuclear stability.'},
    'mass defect':{d:'The difference between the total mass of separated nucleons and the mass of the bound nucleus.',unit:'kg or u',equation:'ΔE = Δmc²',more:'The missing mass corresponds to binding energy released when the nucleus forms.',exam:'Keep units consistent when converting atomic mass units to energy.'},
    'fission':{d:'Splitting of a heavy nucleus into smaller nuclei with energy release and usually additional neutrons.',more:'Energy is released because the products have greater binding energy per nucleon. Emitted neutrons can sustain a chain reaction.',exam:'Conserve nucleon number and charge in nuclear equations.'},
    'fusion':{d:'Combining light nuclei to form a heavier nucleus with energy release.',more:'Fusion releases energy when the product has greater binding energy per nucleon, but high temperatures are required to overcome electrostatic repulsion.',exam:'Do not say mass is “lost”; mass-energy is conserved.'}
  };

  const TOPIC_TERMS={
    measurements:['uncertainty','accuracy','precision','systematic error','random error','resolution','gradient'],
    particles:['photon','quark','baryon','meson','lepton','annihilation','pair production','work function','de broglie wavelength'],
    waves:['amplitude','wavelength','frequency','phase difference','superposition','node','antinode','coherence','diffraction','refractive index','critical angle'],
    mechanics:['displacement','velocity','acceleration','resultant force','momentum','impulse','work','power','stress','strain','young modulus'],
    electricity:['electric current','potential difference','emf','resistance','resistivity','internal resistance','kirchhoff first law','kirchhoff second law'],
    'further-mechanics':['centripetal acceleration','angular velocity','simple harmonic motion','resonance','internal energy','specific heat capacity','ideal gas'],
    fields:['electric field strength','gravitational field strength','electric potential','gravitational potential','capacitance','time constant','magnetic flux density','magnetic flux','faraday law'],
    nuclear:['rutherford scattering','activity','decay constant','half-life','binding energy','mass defect','fission','fusion']
  };

  const TERM_ALIASES={
    'emf':['emf','e.m.f.'],
    'young modulus':["young modulus","young's modulus"],
    'faraday law':["faraday law","faraday's law"],
    'rutherford scattering':['rutherford scattering','alpha scattering'],
    'de broglie wavelength':['de broglie wavelength','de broglie'],
    'simple harmonic motion':['simple harmonic motion','shm'],
    'potential difference':['potential difference','p.d.'],
    'electric current':['electric current','current'],
    'resultant force':['resultant force','net force']
  };

  function safeJson(value,fallback){try{return JSON.parse(value)||fallback}catch{return fallback}}
  function esc(value){return String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function currentCourseTopic(){const id=window.CourseApp?.getState?.().topicId;return id&&data[id]?id:null;}
  function persist(){savedLocation={topic:activeTopic,chapter:activeChapter};localStorage.setItem(locationKey,JSON.stringify(savedLocation));}
  function markRead(){const chapter=data[activeTopic]?.chapters?.[activeChapter];if(!chapter)return;readState[`${activeTopic}:${chapter.id}`]=true;localStorage.setItem(readKey,JSON.stringify(readState));}
  function injectCss(){if(document.querySelector('link[href="textbook.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='textbook.css';document.head.appendChild(link);}

  function build(){
    if(document.getElementById('textbookWorkspace'))return;
    const wrap=document.createElement('section');
    wrap.id='textbookWorkspace';wrap.className='textbook-workspace';wrap.hidden=true;wrap.setAttribute('aria-label','AQA Physics textbook');
    wrap.innerHTML=`<div class="textbook-bar"><button class="textbook-back" id="textbookBack" type="button">← Back</button><div class="textbook-identity"><span>Full course textbook</span><strong id="textbookBarTitle">AQA Physics 7408</strong></div><select class="textbook-select topic-select" id="textbookTopicSelect" aria-label="Choose textbook topic"></select><select class="textbook-select textbook-mobile-chapter" id="textbookMobileChapter" aria-label="Choose textbook chapter"></select><div class="textbook-bar-spacer"></div><button class="textbook-action" data-kind="notes" id="textbookNotes" type="button">Notebook</button><button class="textbook-action" data-kind="ai" id="textbookAI" type="button">AI Coach</button><div class="textbook-progress"><div class="textbook-progress-fill" id="textbookProgressFill"></div></div></div><div class="textbook-layout"><aside class="textbook-sidebar"><div class="textbook-sidebar-head"><span id="textbookSideCode">AQA 3.1</span><strong id="textbookSideTitle">Measurements</strong></div><div class="textbook-chapter-list" id="textbookChapterList"></div></aside><main class="textbook-content-wrap" id="textbookContentWrap"><article class="textbook-article" id="textbookArticle"></article></main></div><div class="textbook-term-layer" id="textbookTermLayer" hidden><button class="textbook-term-scrim" id="textbookTermScrim" type="button" aria-label="Close terminology detail"></button><aside class="textbook-term-panel" role="dialog" aria-modal="true" aria-labelledby="textbookTermTitle"><div class="textbook-term-head"><div><span>Key terminology</span><h2 id="textbookTermTitle">Term</h2></div><button type="button" id="textbookTermClose" aria-label="Close terminology detail">×</button></div><p class="textbook-term-definition" id="textbookTermDefinition"></p><div class="textbook-term-meta" id="textbookTermMeta"></div><div class="textbook-term-more" id="textbookTermMore"></div><div class="textbook-term-exam" id="textbookTermExam"></div></aside></div>`;
    document.body.appendChild(wrap);
    const toast=document.createElement('div');toast.className='textbook-toast';toast.id='textbookToast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast);
  }

  function injectEntryPoints(){
    const homeActions=document.querySelector('.home-actions');
    if(homeActions&&!document.getElementById('homeTextbookBtn')){const b=document.createElement('button');b.className='button quiet';b.id='homeTextbookBtn';b.type='button';b.textContent='▦ Textbook';homeActions.insertBefore(b,document.getElementById('homeNotebookBtn'));b.addEventListener('click',()=>open());}
    const jump=document.querySelector('.course-jump-inner');
    if(jump&&!document.getElementById('textbookToggle')){const b=document.createElement('button');b.className='button textbook-shell-button';b.id='textbookToggle';b.type='button';b.innerHTML='<span>▦</span> Textbook';jump.insertBefore(b,document.getElementById('notebookToggle'));b.addEventListener('click',()=>open(currentCourseTopic()));}
    const toolBar=document.querySelector('.tool-bar');
    if(toolBar&&!document.getElementById('toolTextbook')){const b=document.createElement('button');b.className='tool-action accent';b.id='toolTextbook';b.type='button';b.dataset.icon='▦';b.textContent='Textbook';toolBar.insertBefore(b,document.getElementById('toolNotebook'));b.addEventListener('click',()=>open());}
  }

  function topicLabel(id){const item=data[id];return item?`${item.code} · ${item.title}`:id;}
  function normaliseChapter(){const chapters=data[activeTopic]?.chapters||[];activeChapter=Math.min(Math.max(Number(activeChapter)||0,0),Math.max(0,chapters.length-1));return chapters;}
  function setTopic(id,{resetChapter=true}={}){if(!data[id])return;activeTopic=id;if(resetChapter)activeChapter=0;normaliseChapter();persist();render();}
  function setChapter(index){const chapters=data[activeTopic]?.chapters||[];activeChapter=Math.min(Math.max(Number(index)||0,0),Math.max(0,chapters.length-1));persist();closeTerm();render();document.getElementById('textbookContentWrap')?.scrollTo({top:0,behavior:'smooth'});}
  function chapterReadCount(topicId){return (data[topicId]?.chapters||[]).filter(c=>readState[`${topicId}:${c.id}`]).length;}

  function renderSelectors(){
    const topicSelect=document.getElementById('textbookTopicSelect');const mobile=document.getElementById('textbookMobileChapter');const chapters=data[activeTopic]?.chapters||[];
    if(!topicSelect||!mobile)return;
    topicSelect.innerHTML=topicOrder.map(id=>`<option value="${esc(id)}">${esc(topicLabel(id))}</option>`).join('');topicSelect.value=activeTopic;
    mobile.innerHTML=chapters.map((c,i)=>`<option value="${i}">${i+1}. ${esc(c.title.replace(/^\d+\.\s*/,''))}</option>`).join('');mobile.value=String(activeChapter);
  }

  function renderSidebar(){
    const topic=data[activeTopic];const list=document.getElementById('textbookChapterList');if(!topic||!list)return;
    const code=document.getElementById('textbookSideCode'),title=document.getElementById('textbookSideTitle');if(code)code.textContent=topic.code;if(title)title.textContent=topic.title;
    list.innerHTML=topic.chapters.map((c,i)=>`<button type="button" class="textbook-chapter-button ${i===activeChapter?'active':''}" data-chapter="${i}">${readState[`${activeTopic}:${c.id}`]?'✓ ':''}${esc(c.title)}</button>`).join('');
    list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>setChapter(Number(b.dataset.chapter))));
  }

  function aliasesFor(key){return TERM_ALIASES[key]||[key];}
  function chapterText(chapter){return [chapter.title,chapter.summary,...(chapter.sections||[]).flat(),...(chapter.equations||[]).flat()].join(' ').toLowerCase();}
  function chapterTermKeys(topicId,chapter){
    const source=chapterText(chapter);const found=[];
    Object.keys(TERM_INFO).forEach(key=>{if(aliasesFor(key).some(a=>source.includes(a.toLowerCase())))found.push(key);});
    for(const key of TOPIC_TERMS[topicId]||[])if(!found.includes(key))found.push(key);
    return found.slice(0,10);
  }

  function linkedText(value,keys){
    const text=String(value??'');const aliases=[];const canonical=new Map();
    keys.forEach(key=>aliasesFor(key).forEach(alias=>{aliases.push(alias);canonical.set(alias.toLowerCase(),key);}));
    aliases.sort((a,b)=>b.length-a.length);
    if(!aliases.length)return esc(text);
    const pattern=new RegExp(`(${aliases.map(a=>a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')})`,'gi');
    return text.split(pattern).map(part=>{const key=canonical.get(part.toLowerCase());return key?`<button class="textbook-term-link" type="button" data-term="${esc(key)}">${esc(part)}</button>`:esc(part);}).join('');
  }

  function equationMarkup(e,terms){return `<div class="textbook-equation"><strong>${linkedText(e[0],terms)}</strong><code>${esc(e[1])}</code><span>${esc(e[2]||'')}</span></div>`;}

  function svgFigure(title,caption,body){return `<figure class="textbook-diagram"><div class="textbook-diagram-label">Concept diagram</div><svg viewBox="0 0 720 300" role="img" aria-label="${esc(title)}"><defs><marker id="tbArrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" class="diagram-arrowhead"></path></marker></defs>${body}</svg><figcaption><strong>${esc(title)}</strong><span>${esc(caption)}</span></figcaption></figure>`;}
  const line=(x1,y1,x2,y2,cls='diagram-line',arrow=false)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" class="${cls}"${arrow?' marker-end="url(#tbArrow)"':''}></line>`;
  const txt=(x,y,t,cls='diagram-text',anchor='middle')=>`<text x="${x}" y="${y}" class="${cls}" text-anchor="${anchor}">${esc(t)}</text>`;
  const circle=(x,y,r,cls='diagram-node')=>`<circle cx="${x}" cy="${y}" r="${r}" class="${cls}"></circle>`;
  const path=(d,cls='diagram-line')=>`<path d="${d}" class="${cls}" fill="none"></path>`;
  function rect(x,y,w,h,cls='diagram-block'){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="10" class="${cls}"></rect>`;}

  function diagramForChapter(topicId,chapter){
    const s=chapterText(chapter);
    if(/unit|prefix|dimension/.test(s)&&topicId==='measurements')return svgFigure('SI scale and dimensional consistency','Convert prefixes before substitution and use dimensions to check equations.',`${line(90,150,630,150,'diagram-axis',true)}${[120,240,360,480,600].map((x,i)=>`${line(x,135,x,165,'diagram-line')}${txt(x,195,['10⁻⁶','10⁻³','10⁰','10³','10⁶'][i])}`).join('')}${txt(120,112,'micro')}${txt(240,112,'milli')}${txt(360,112,'base SI')}${txt(480,112,'kilo')}${txt(600,112,'mega')}`);
    if(/uncertainty|random|systematic|precision|accuracy/.test(s)&&topicId==='measurements')return svgFigure('Random and systematic measurement effects','Random error produces spread; systematic error shifts the whole set away from the accepted value.',`${line(90,235,630,235,'diagram-axis')}${line(360,50,360,255,'diagram-guide')}${txt(360,278,'accepted value')}${[300,330,355,380,410].map((x,i)=>circle(x,105+(i%2)*18,9,'diagram-node')).join('')}${[455,480,500,520,545].map((x,i)=>circle(x,175+(i%2)*16,9,'diagram-node-warn')).join('')}${txt(350,65,'random spread')}${txt(510,135,'systematic shift')}`);
    if(/graph|gradient|log/.test(s)&&topicId==='measurements')return svgFigure('Linear graph interpretation','The gradient and intercept of a best-fit line can reveal physical constants.',`${line(110,240,110,55,'diagram-axis',true)}${line(110,240,650,240,'diagram-axis',true)}${line(150,220,590,75,'diagram-accent')}${line(210,200,510,200,'diagram-guide')}${line(510,200,510,102,'diagram-guide')}${txt(530,158,'Δy')}${txt(360,222,'Δx')}${txt(335,55,'gradient = Δy / Δx')}`);
    if(/quark|proton|neutron|hadron|baryon|meson/.test(s)&&topicId==='particles')return svgFigure('Quark structure of nucleons','Protons are uud and neutrons are udd; fractional quark charges sum to the nucleon charge.',`${circle(230,150,86,'diagram-shell')}${circle(490,150,86,'diagram-shell')}${circle(205,125,25,'diagram-node')}${circle(255,125,25,'diagram-node')}${circle(230,175,25,'diagram-node-warn')}${txt(205,131,'u')}${txt(255,131,'u')}${txt(230,181,'d')}${circle(465,125,25,'diagram-node')}${circle(515,125,25,'diagram-node-warn')}${circle(490,175,25,'diagram-node-warn')}${txt(465,131,'u')}${txt(515,131,'d')}${txt(490,181,'d')}${txt(230,270,'proton +e')}${txt(490,270,'neutron 0')}`);
    if(/photoelectric|work function|threshold|photon/.test(s)&&topicId==='particles')return svgFigure('Photoelectric effect','One photon transfers energy to one electron; emission occurs only if hf is at least the work function.',`${path('M90 80 L220 150 L90 220','diagram-wave')}${txt(105,62,'photon hf','diagram-text','start')}${line(230,65,230,235,'diagram-surface')}${line(230,95,620,95,'diagram-surface')}${line(230,135,620,135,'diagram-guide')}${line(230,175,620,175,'diagram-guide')}${circle(300,95,10,'diagram-node')}${line(310,92,520,55,'diagram-accent',true)}${txt(535,55,'electron Eₖ','diagram-text','start')}${txt(410,222,'metal surface / energy states')}`);
    if(/de broglie|duality|electron diffraction/.test(s)&&topicId==='particles')return svgFigure('Electron diffraction','A beam of electrons passing through a crystal produces a diffraction pattern, evidence of wave behaviour.',`${line(85,150,260,150,'diagram-accent',true)}${txt(90,130,'electron beam','diagram-text','start')}${line(280,70,280,230,'diagram-surface')}${[310,340,370].map((x,i)=>line(280,150,x,95+i*55,'diagram-wave')).join('')}${line(610,60,610,240,'diagram-surface')}${[90,125,150,175,210].map(y=>circle(610,y,7,'diagram-node')).join('')}${txt(610,275,'diffraction pattern')}`);
    if(/stationary|node|antinode|superposition/.test(s)&&topicId==='waves')return svgFigure('Stationary wave pattern','Nodes remain at zero amplitude while antinodes oscillate with maximum amplitude.',`${line(80,150,640,150,'diagram-axis')}${path('M80 150 C130 60 180 60 230 150 C280 240 330 240 380 150 C430 60 480 60 530 150 C580 240 620 220 640 150','diagram-accent')}${[80,230,380,530,640].map(x=>circle(x,150,6,'diagram-node')).join('')}${txt(230,285,'nodes separated by λ/2')}`);
    if(/interference|double slit|diffraction|coherent|fringe/.test(s)&&topicId==='waves')return svgFigure('Two-source interference','Coherent waves from two slits overlap to form alternating constructive and destructive fringes.',`${line(80,150,220,150,'diagram-accent',true)}${line(240,55,240,120,'diagram-surface')}${line(240,180,240,245,'diagram-surface')}${circle(240,140,6,'diagram-node')}${circle(240,160,6,'diagram-node')}${[0,1,2].map(i=>path(`M246 140 Q${360+i*25} ${80+i*45} 610 ${70+i*80}`,'diagram-wave')).join('')}${[0,1,2].map(i=>path(`M246 160 Q${360+i*25} ${220-i*45} 610 ${230-i*80}`,'diagram-wave')).join('')}${line(630,45,630,255,'diagram-surface')}${txt(630,280,'screen fringes')}`);
    if(/refraction|critical angle|total internal/.test(s)&&topicId==='waves')return svgFigure('Refraction and total internal reflection','Angles are measured from the normal. Above the critical angle in the denser medium, the ray reflects internally.',`${line(70,150,650,150,'diagram-surface')}${line(360,40,360,260,'diagram-guide')}${line(150,55,360,150,'diagram-accent',true)}${line(360,150,540,230,'diagram-wave',true)}${line(360,150,570,75,'diagram-warn',true)}${txt(390,35,'normal')}${txt(220,105,'incident')}${txt(500,235,'refracted')}${txt(530,65,'TIR path')}`);
    if(/progressive|wave speed|phase|transverse|longitudinal/.test(s)&&topicId==='waves')return svgFigure('Progressive wave quantities','Amplitude is measured from equilibrium; wavelength is the distance between adjacent points in phase.',`${line(70,150,650,150,'diagram-axis')}${path('M70 150 C120 55 170 55 220 150 C270 245 320 245 370 150 C420 55 470 55 520 150 C570 245 620 235 650 150','diagram-accent')}${line(145,150,145,76,'diagram-guide')}${txt(155,110,'A','diagram-text','start')}${line(145,55,445,55,'diagram-guide')}${txt(295,42,'λ')}`);
    if(/stress|strain|young|elastic|material/.test(s)&&topicId==='mechanics')return svgFigure('Stress–strain behaviour','The initial gradient gives Young modulus; beyond the elastic region permanent deformation can occur.',`${line(110,240,110,50,'diagram-axis',true)}${line(110,240,650,240,'diagram-axis',true)}${path('M110 240 L310 105 C360 82 405 86 450 120 C505 155 560 175 620 165','diagram-accent')}${txt(310,82,'linear elastic')}${txt(520,210,'strain')}${txt(70,78,'stress')}`);
    if(/momentum|impulse|collision/.test(s)&&topicId==='mechanics')return svgFigure('Momentum in a collision','For a closed system, total momentum before equals total momentum after.',`${rect(105,118,120,64,'diagram-block')}${rect(475,118,120,64,'diagram-block')}${line(230,150,330,150,'diagram-accent',true)}${line(470,150,390,150,'diagram-warn',true)}${txt(165,205,'m₁u₁')}${txt(535,205,'m₂u₂')}${txt(350,70,'Σp before = Σp after')}`);
    if(/projectile|force|newton|motion|kinematic|energy|work|power/.test(s)&&topicId==='mechanics')return svgFigure('Forces and motion','Resolve the actual forces first; the resultant force sets the acceleration.',`${rect(290,115,140,80,'diagram-block')}${line(360,115,360,55,'diagram-accent',true)}${line(360,195,360,255,'diagram-warn',true)}${line(290,155,210,155,'diagram-line',true)}${line(430,155,520,155,'diagram-line',true)}${txt(375,55,'normal','diagram-text','start')}${txt(375,270,'weight','diagram-text','start')}${txt(190,145,'resistance')}${txt(535,145,'drive')}`);
    if(/resistivity|resistance|i-v|ohmic|current|charge/.test(s)&&topicId==='electricity')return svgFigure('Current, potential difference and resistance','Current flows around the circuit; potential difference is measured across the component.',`${path('M130 85 H590 V215 H130 Z','diagram-wire')}${line(335,85,385,85,'diagram-surface')}${rect(320,70,80,30,'diagram-component')}${txt(360,55,'R')}${circle(500,150,32,'diagram-meter')}${txt(500,157,'A')}${line(320,215,400,215,'diagram-surface')}${line(342,205,342,225,'diagram-surface')}${line(375,197,375,233,'diagram-surface')}${txt(360,265,'source')}`);
    if(/kirchhoff|series|parallel|potential divider|circuit/.test(s)&&topicId==='electricity')return svgFigure('Series and parallel circuit reasoning','Use charge conservation at junctions and energy conservation around loops.',`${path('M100 75 H620 V225 H100 Z','diagram-wire')}${path('M260 75 V225','diagram-wire')}${path('M470 75 V225','diagram-wire')}${rect(240,115,40,70,'diagram-component')}${rect(450,115,40,70,'diagram-component')}${circle(100,150,6,'diagram-node')}${circle(620,150,6,'diagram-node')}${line(140,150,220,150,'diagram-accent',true)}${txt(360,45,'parallel branches')}`);
    if(/circular|centripetal|angular/.test(s)&&topicId==='further-mechanics')return svgFigure('Uniform circular motion','Velocity is tangential while centripetal acceleration and resultant force point toward the centre.',`${circle(360,150,95,'diagram-orbit')}${circle(360,150,6,'diagram-node')}${circle(440,95,12,'diagram-node-warn')}${line(440,95,360,150,'diagram-accent',true)}${line(440,95,520,150,'diagram-line',true)}${txt(330,120,'a, F')}${txt(535,155,'v')}`);
    if(/simple harmonic|shm|oscillat|resonance/.test(s)&&topicId==='further-mechanics')return svgFigure('Simple harmonic motion','Acceleration is directed toward equilibrium and proportional to displacement.',`${line(80,150,640,150,'diagram-axis')}${path('M90 150 C145 55 205 55 260 150 C315 245 375 245 430 150 C485 55 545 55 610 150','diagram-accent')}${line(350,55,350,245,'diagram-guide')}${txt(350,280,'equilibrium')}${txt(155,60,'x = +A')}${txt(375,235,'x = −A')}`);
    if(/thermal|internal energy|specific heat|ideal gas|gas law|molecular/.test(s)&&topicId==='further-mechanics')return svgFigure('Kinetic model of a gas','Gas pressure arises from particle collisions with the container walls; higher temperature means greater mean kinetic energy.',`${rect(150,55,420,190,'diagram-shell')}${[[200,100,35,-20],[280,185,-45,20],[365,115,40,30],[455,190,-30,-35],[510,95,35,20],[330,220,45,-10]].map(([x,y,dx,dy])=>`${circle(x,y,9,'diagram-node')}${line(x,y,x+dx,y+dy,'diagram-accent',true)}`).join('')}${txt(360,275,'pV = nRT')}`);
    if(/capacitor|capacitance|time constant/.test(s)&&topicId==='fields')return svgFigure('Capacitor charging and field','Opposite charge builds on the plates; voltage and charge change exponentially through a resistor.',`${line(260,70,260,230,'diagram-surface')}${line(390,70,390,230,'diagram-surface')}${['+','+','+','+'].map((t,i)=>txt(240,95+i*38,t,'diagram-charge')).join('')}${['−','−','−','−'].map((t,i)=>txt(410,95+i*38,t,'diagram-charge')).join('')}${[100,140,180,220].map(y=>line(285,y,365,y,'diagram-accent',true)).join('')}${txt(325,270,'uniform field between plates')}`);
    if(/magnetic|flux|induction|faraday|transformer/.test(s)&&topicId==='fields')return svgFigure('Electromagnetic induction','Changing magnetic flux linkage through a coil induces an emf; the induced effect opposes the change.',`${rect(110,95,125,110,'diagram-magnet')}${txt(140,155,'N')}${txt(205,155,'S')}${[280,310,340,370,400].map(x=>path(`M${x} 80 C${x-25} 120 ${x-25} 180 ${x} 220`,'diagram-coil')).join('')}${line(235,150,500,150,'diagram-accent',true)}${txt(420,120,'changing Φ')}${circle(565,150,34,'diagram-meter')}${txt(565,157,'V')}`);
    if(/electric field|gravitational field|potential|inverse square|field strength/.test(s)&&topicId==='fields')return svgFigure('Radial fields and potential','Field vectors are radial; field strength varies as 1/r² while point-source potential varies as 1/r.',`${circle(360,150,20,'diagram-source')}${[0,45,90,135,180,225,270,315].map(a=>{const r=a*Math.PI/180;return line(360+28*Math.cos(r),150+28*Math.sin(r),360+125*Math.cos(r),150+125*Math.sin(r),'diagram-accent',true)}).join('')}${circle(360,150,82,'diagram-guide-circle')}${txt(360,285,'E ∝ 1/r²    V ∝ 1/r')}`);
    if(/rutherford|scattering|closest approach/.test(s)&&topicId==='nuclear')return svgFigure('Rutherford alpha scattering','Most alpha particles pass through; a small number are strongly deflected by the compact positive nucleus.',`${circle(480,150,18,'diagram-source')}${[85,115,145,175,205].map(y=>line(80,y,420,y,'diagram-accent',true)).join('')}${path('M420 145 Q455 100 610 70','diagram-warn')}${path('M420 155 Q455 200 610 240','diagram-warn')}${txt(480,45,'small + nucleus')}${txt(130,65,'α beam')}`);
    if(/radioactive|activity|decay|half-life/.test(s)&&topicId==='nuclear')return svgFigure('Exponential radioactive decay','The number of undecayed nuclei and activity fall exponentially; equal half-lives give repeated halving.',`${line(100,245,100,50,'diagram-axis',true)}${line(100,245,650,245,'diagram-axis',true)}${path('M110 65 C210 85 275 125 335 165 C410 210 505 230 630 240','diagram-accent')}${line(100,155,335,155,'diagram-guide')}${line(335,155,335,245,'diagram-guide')}${txt(335,270,'T½')}${txt(75,160,'½N₀')}`);
    if(/binding|mass defect|fission|fusion|nuclear energy/.test(s)&&topicId==='nuclear')return svgFigure('Binding energy per nucleon','Energy is released when nuclear reactions move nuclei toward greater binding energy per nucleon.',`${line(95,240,95,55,'diagram-axis',true)}${line(95,240,650,240,'diagram-axis',true)}${path('M105 225 C145 150 190 95 255 78 C340 58 430 70 620 110','diagram-accent')}${txt(265,58,'iron region')}${txt(160,210,'fusion')}${txt(540,150,'fission')}`);
    const fallbacks={measurements:'Measurement model',particles:'Particle interaction model',waves:'Wave model',mechanics:'Force model',electricity:'Circuit model','further-mechanics':'Dynamic model',fields:'Field model',nuclear:'Nuclear model'};
    return svgFigure(fallbacks[topicId]||'Physics model','Use the diagram alongside the chapter explanation to connect quantities, directions and relationships.',`${line(120,150,600,150,'diagram-axis',true)}${circle(220,150,34,'diagram-node')}${circle(500,150,34,'diagram-node-warn')}${line(255,150,455,150,'diagram-accent',true)}${txt(360,115,'physical relationship')}`);
  }

  function terminologyMarkup(keys){
    if(!keys.length)return'';
    return `<section class="textbook-terminology"><div class="textbook-callout-label">Key terminology</div><h2>Key terminology for this chapter</h2><p class="textbook-terminology-intro">Select any term for a fuller explanation and exam-use guidance.</p><div class="textbook-term-grid">${keys.map(key=>`<button class="textbook-term-card" type="button" data-term="${esc(key)}"><strong>${esc(key)}</strong><span>${esc(TERM_INFO[key]?.d||'Open definition')}</span><em>More information →</em></button>`).join('')}</div></section>`;
  }

  function renderArticle(){
    const topic=data[activeTopic],chapter=topic?.chapters?.[activeChapter],article=document.getElementById('textbookArticle');if(!topic||!chapter||!article)return;
    const terms=chapterTermKeys(activeTopic,chapter);
    const sections=chapter.sections.map(([heading,body])=>`<section class="textbook-section"><h2>${linkedText(heading,terms)}</h2><p>${linkedText(body,terms)}</p></section>`).join('');
    const equations=(chapter.equations||[]).length?`<div class="textbook-equations">${chapter.equations.map(e=>equationMarkup(e,terms)).join('')}</div>`:'';
    const example=chapter.example?`<section class="textbook-example"><div class="textbook-callout-label">Worked example</div><h3>${linkedText(chapter.example.q,terms)}</h3><ol>${(chapter.example.steps||[]).map(s=>`<li>${linkedText(s,terms)}</li>`).join('')}</ol><div class="textbook-answer">Answer: ${linkedText(chapter.example.answer,terms)}</div></section>`:'';
    const tip=chapter.examTip?`<aside class="textbook-tip"><div class="textbook-callout-label">Exam tip</div><p>${linkedText(chapter.examTip,terms)}</p></aside>`:'';
    const checks=(chapter.checks||[]).length?`<section class="textbook-check"><div class="textbook-callout-label">Check your understanding</div><h3>Retrieval questions</h3><ol>${chapter.checks.map(q=>`<li>${linkedText(q,terms)}</li>`).join('')}</ol></section>`:'';
    article.innerHTML=`<div class="textbook-topic-kicker"><span>${esc(topic.code)}</span>${esc(topic.year)} · Chapter ${activeChapter+1} of ${topic.chapters.length}</div><h1>${linkedText(chapter.title,terms)}</h1><p class="textbook-summary">${linkedText(chapter.summary,terms)}</p>${diagramForChapter(activeTopic,chapter)}${terminologyMarkup(terms)}${sections}${equations}${example}${tip}${checks}<div class="textbook-chapter-actions"><button class="textbook-save" type="button" id="textbookSaveSummary">▤ Save chapter summary</button>${chapter.example?'<button class="textbook-save" type="button" id="textbookSaveExample">▤ Save worked example</button>':''}<button class="textbook-save" type="button" id="textbookMarkRead">✓ Mark chapter read</button></div>`;
    article.querySelectorAll('[data-term]').forEach(button=>button.addEventListener('click',()=>openTerm(button.dataset.term,button)));
    document.getElementById('textbookSaveSummary')?.addEventListener('click',()=>saveToNotebook(`${chapter.title}\n${chapter.summary}`,chapter));
    document.getElementById('textbookSaveExample')?.addEventListener('click',()=>saveToNotebook(`${chapter.example.q}\n${(chapter.example.steps||[]).join(' ')}\nAnswer: ${chapter.example.answer}`,chapter));
    document.getElementById('textbookMarkRead')?.addEventListener('click',()=>{markRead();showToast('Chapter marked as read');renderSidebar();updateProgress();});
    const barTitle=document.getElementById('textbookBarTitle');if(barTitle)barTitle.textContent=`${topic.code} · ${topic.title}`;
  }

  function openTerm(key,trigger){
    const info=TERM_INFO[key];const layer=document.getElementById('textbookTermLayer');if(!info||!layer)return;
    const title=document.getElementById('textbookTermTitle'),definition=document.getElementById('textbookTermDefinition'),meta=document.getElementById('textbookTermMeta'),more=document.getElementById('textbookTermMore'),exam=document.getElementById('textbookTermExam');
    if(title)title.textContent=key;if(definition)definition.textContent=info.d||'';
    if(meta)meta.innerHTML=[info.unit?`<span><strong>Unit</strong>${esc(info.unit)}</span>`:'',info.equation?`<span><strong>Useful relationship</strong><code>${esc(info.equation)}</code></span>`:''].filter(Boolean).join('');
    if(more)more.innerHTML=info.more?`<h3>What it means in Physics</h3><p>${esc(info.more)}</p>`:'';
    if(exam)exam.innerHTML=info.exam?`<h3>Exam use</h3><p>${esc(info.exam)}</p>`:'';
    layer.hidden=false;layer._returnFocus=trigger||document.activeElement;document.getElementById('textbookTermClose')?.focus({preventScroll:true});
  }

  function closeTerm(){const layer=document.getElementById('textbookTermLayer');if(!layer||layer.hidden)return false;layer.hidden=true;const target=layer._returnFocus;layer._returnFocus=null;target?.focus?.({preventScroll:true});return true;}
  function updateProgress(){const topic=data[activeTopic];const done=chapterReadCount(activeTopic);const fill=document.getElementById('textbookProgressFill');if(fill&&topic)fill.style.width=`${topic.chapters.length?done/topic.chapters.length*100:0}%`;}
  function render(){if(!data[activeTopic])activeTopic=topicOrder[0]||Object.keys(data)[0];normaliseChapter();renderSelectors();renderSidebar();renderArticle();updateProgress();}
  function showToast(message){const toast=document.getElementById('textbookToast');if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700);}
  function saveToNotebook(text,chapter){const topic=data[activeTopic];const ok=window.CourseNotebook?.save?.(text,{topicId:activeTopic,code:topic.code,title:topic.title,moduleLabel:'Textbook',sectionTitle:chapter.title,pageTitle:'AQA Physics Textbook',sourceType:'selection'});if(ok)showToast('Saved to notebook');}

  function open(topicId,chapterIndex){
    lastTrigger=document.activeElement;
    document.getElementById('coachClose')?.click();window.CourseNotebook?.close?.();closeTerm();
    const wanted=topicId&&data[topicId]?topicId:(currentCourseTopic()||activeTopic||topicOrder[0]);
    const topicChanged=wanted!==activeTopic;activeTopic=wanted;
    if(chapterIndex!==undefined&&Number.isInteger(Number(chapterIndex)))activeChapter=Number(chapterIndex);else if(topicChanged)activeChapter=0;
    normaliseChapter();persist();
    const workspace=document.getElementById('textbookWorkspace');if(!workspace)return;workspace.hidden=false;document.documentElement.classList.add('textbook-open');document.body.style.overflow='hidden';
    render();
    requestAnimationFrame(()=>{render();document.getElementById('textbookBack')?.focus({preventScroll:true});window.dispatchEvent(new CustomEvent('textbookchange',{detail:{open:true,topicId:activeTopic,chapterIndex:activeChapter}}));});
  }
  function close(){if(closeTerm())return;const workspace=document.getElementById('textbookWorkspace');if(!workspace||workspace.hidden)return;workspace.hidden=true;document.documentElement.classList.remove('textbook-open');document.body.style.overflow='';lastTrigger?.focus?.({preventScroll:true});window.dispatchEvent(new CustomEvent('textbookchange',{detail:{open:false}}));}
  function nextChapter(){const chapters=data[activeTopic]?.chapters||[];if(activeChapter<chapters.length-1)setChapter(activeChapter+1);}
  function previousChapter(){if(activeChapter>0)setChapter(activeChapter-1);}

  injectCss();build();injectEntryPoints();render();
  document.getElementById('textbookBack')?.addEventListener('click',close);
  document.getElementById('textbookTopicSelect')?.addEventListener('change',e=>setTopic(e.target.value));
  document.getElementById('textbookMobileChapter')?.addEventListener('change',e=>setChapter(Number(e.target.value)));
  document.getElementById('textbookNotes')?.addEventListener('click',()=>window.CourseNotebook?.open?.({topicId:activeTopic}));
  document.getElementById('textbookAI')?.addEventListener('click',()=>document.getElementById('coachToggle')?.click());
  document.getElementById('textbookTermClose')?.addEventListener('click',closeTerm);
  document.getElementById('textbookTermScrim')?.addEventListener('click',closeTerm);
  window.addEventListener('message',event=>{const d=event.data||{};if(d.type==='alevel-textbook-open')open(d.topicId||currentCourseTopic());});
  document.addEventListener('keydown',event=>{const openNow=!document.getElementById('textbookWorkspace')?.hidden;if(!openNow)return;if(event.key==='Escape'){event.preventDefault();if(!closeTerm())close();return;}if(document.getElementById('textbookTermLayer')&&!document.getElementById('textbookTermLayer').hidden)return;if(event.altKey&&event.key==='ArrowRight'){event.preventDefault();nextChapter();}if(event.altKey&&event.key==='ArrowLeft'){event.preventDefault();previousChapter();}});
  window.CourseTextbook={open,close,setTopic,setChapter,openTerm,getState:()=>({topicId:activeTopic,chapterIndex:activeChapter,read:{...readState}}),data,terms:TERM_INFO};
})();