(()=>{
'use strict';
const DATA=window.ALEVEL_ASSESSMENT_DATA;
if(!DATA)return;
const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
let subject=['biology','chemistry'].includes(params.get('subject'))?params.get('subject'):'biology';
let session=null,timerId=null,secondsLeft=0;
const stopWords=new Set('the a an and or of to in is are was were be been being for from with as by on at that this these those it its into when where which who how why can could should would may might must do does did has have had using use used student students explain evaluate analyse analyze describe state calculate determine compare discuss suggest give one two three four linked relevant answer science scientific chemistry biology'.split(' '));
const storeKey=s=>`alevel-${s}-assessment-history-v1`;
const safeJSON=(s,f)=>{try{return JSON.parse(s)||f}catch{return f}};
const history=()=>{const h=safeJSON(localStorage.getItem(storeKey(subject)),[]);return Array.isArray(h)?h:[]};
const bank=()=>DATA.getBank(subject);
const config=()=>DATA.exam[subject];
const topics=()=>DATA.topicLabels[subject];
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1800)}
function setView(id){document.querySelectorAll('.view').forEach(v=>{v.hidden=v.id!==id;v.classList.toggle('active',v.id===id)});document.querySelectorAll('.side-nav').forEach(b=>b.classList.toggle('active',`${b.dataset.view}View`===id));}
function paperText(){const p=config().papers;return Object.values(p).map(x=>`<p><strong>${x.label}</strong> · ${x.marks} marks · ${x.scope}</p>`).join('')}
function updateIdentity(){
 const proper=subject[0].toUpperCase()+subject.slice(1),code=config().code,b=bank(),h=history();
 document.title=`AQA A-Level ${proper} Assessment Hub`;$('brandTitle').textContent=`A-Level ${proper} Assessment Hub`;$('brandSub').textContent=`AQA ${code} · Exam practice`;$('backLink').href=`../index.html?subject=${subject}`;$('heroEyebrow').textContent=`AQA ${proper} ${code}`;$('heroBankCount').textContent=b.length;$('bankCount').textContent=`${b.length} questions`;$('attemptCount').textContent=`${h.length} saved attempt${h.length===1?'':'s'}`;$('examMap').innerHTML=`<h3>${proper} exam map</h3>${paperText()}`;
 document.querySelectorAll('[data-subject]').forEach(x=>x.classList.toggle('active',x.dataset.subject===subject));
 renderTopicOptions();renderCoverage();renderDashboard();renderHistory();updateSetupSummary();
}
function renderTopicOptions(){const select=$('topicSelect'),current=select.value;select.innerHTML='<option value="all">All topics</option>'+Object.entries(topics()).map(([k,v])=>`<option value="${k}">${k} · ${v}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}
function renderCoverage(){const b=bank();$('coverageGrid').innerHTML=Object.entries(topics()).map(([k,label])=>{const q=b.filter(x=>x.topic===k);const aos=new Set(q.map(x=>x.ao));return `<article class="coverage-card"><strong>${k} · ${label}</strong><span>${q.length} questions · ${[...aos].join(' / ')}</span></article>`}).join('')}
function updateSetupSummary(){const mode=$('modeSelect').value,count=$('countSelect').value,topic=$('topicSelect').value,ao=$('aoSelect').value,timed=$('timedToggle').checked;const modeLabel=$('modeSelect').selectedOptions[0]?.textContent||mode;const topicLabel=topic==='all'?'all specification topics':topics()[topic]||topic;const aoLabel=ao==='all'?'balanced AO1/AO2/AO3':ao;$('setupSummary').textContent=`${modeLabel}: ${count} questions from ${topicLabel}, ${aoLabel}${timed?', timed':''}. Instant marks are formative estimates and the indicative mark points remain available for review.`}
function questionPool(){let q=[...bank()];const mode=$('modeSelect').value,topic=$('topicSelect').value,ao=$('aoSelect').value;if(topic!=='all')q=q.filter(x=>x.topic===topic);if(ao!=='all')q=q.filter(x=>x.ao===ao);if(mode==='paper1')q=q.filter(x=>x.papers.includes('paper1'));if(mode==='paper2')q=q.filter(x=>x.papers.includes('paper2'));if(mode==='paper3')q=q.filter(x=>x.papers.includes('paper3'));if(mode==='practical'||$('practicalToggle').checked)q=q.filter(x=>x.practical);if(mode==='ao'&&ao==='all')q=q.filter(x=>x.ao==='AO3');return q}
function shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function balancedPick(pool,count){if(!pool.length)return[];const picked=[];const groups={AO1:pool.filter(x=>x.ao==='AO1'),AO2:pool.filter(x=>x.ao==='AO2'),AO3:pool.filter(x=>x.ao==='AO3')};while(picked.length<count&&picked.length<pool.length){for(const ao of ['AO1','AO2','AO3']){const g=groups[ao].filter(x=>!picked.includes(x));if(g.length&&picked.length<count)picked.push(g[Math.floor(Math.random()*g.length)])}}if(picked.length<count){for(const q of shuffle([...pool]))if(!picked.includes(q)&&picked.length<count)picked.push(q)}return picked}
function startSession(){const pool=questionPool(),count=Math.min(Number($('countSelect').value)||10,pool.length);if(!pool.length){toast('No questions match those filters.');return}const qs=$('aoSelect').value==='all'?balancedPick(pool,count):shuffle([...pool]).slice(0,count);session={subject,mode:$('modeSelect').value,questions:qs,index:0,answers:[],started:Date.now(),timed:$('timedToggle').checked};if(session.timed){secondsLeft=Math.max(300,qs.reduce((s,q)=>s+q.marks*90,0));startTimer()}else{$('timer').hidden=true}setView('sessionView');renderQuestion()}
function startTimer(){clearInterval(timerId);$('timer').hidden=false;renderTimer();timerId=setInterval(()=>{secondsLeft--;renderTimer();if(secondsLeft<=0){clearInterval(timerId);toast('Time is up — finishing this set.');finishSession()}},1000)}
function renderTimer(){const m=Math.floor(secondsLeft/60),s=secondsLeft%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function current(){return session?.questions?.[session.index]}
function renderQuestion(){const q=current();if(!q){finishSession();return}$('questionProgress').textContent=`Question ${session.index+1} of ${session.questions.length}`;$('questionProgressBar').style.width=`${session.index/session.questions.length*100}%`;$('scoreLive').textContent=`${session.answers.reduce((s,a)=>s+a.score,0)} marks`;$('qRef').textContent=q.ref;$('qAO').textContent=q.ao;$('qPaper').textContent=q.papers.map(p=>config().papers[p]?.label).filter(Boolean).join(' / ');$('qMarks').textContent=`${q.marks} marks`;$('qPrompt').textContent=q.prompt;$('qContext').textContent=q.context||'';$('answerInput').value='';$('answerInput').disabled=false;$('feedbackPanel').hidden=true;$('markBtn').disabled=false;$('skipBtn').disabled=false;$('answerInput').focus()}
function words(s){return cleanText(s).split(' ').filter(w=>w.length>3&&!stopWords.has(w))}
function cleanText(s){return String(s||'').toLowerCase().replace(/[^a-z0-9%+\- ]+/g,' ').replace(/\s+/g,' ').trim()}
function pointHit(answer,point,terms){const a=new Set(words(answer)),p=words(point);const important=[...new Set([...p,...terms.flatMap(words)])];const overlap=important.filter(w=>a.has(w));const target=Math.min(2,Math.max(1,Math.ceil(p.length*.2)));return overlap.length>=target}
function markAnswer(){const q=current(),answer=$('answerInput').value.trim();if(!q)return;const hits=q.markPoints.map(p=>pointHit(answer,p,q.terms||[]));let score=Math.min(q.marks,hits.filter(Boolean).length);if(answer.length<10)score=0;const missing=q.markPoints.filter((_,i)=>!hits[i]);session.answers.push({id:q.id,ref:q.ref,topic:q.topic,ao:q.ao,marks:q.marks,score,answer});$('answerInput').disabled=true;$('markBtn').disabled=true;$('skipBtn').disabled=true;$('feedbackScore').textContent=`${score} / ${q.marks}`;$('feedbackLabel').textContent=score===q.marks?'Strong answer':score>=Math.ceil(q.marks/2)?'Partly secure':'Needs development';$('markPoints').innerHTML=q.markPoints.map((p,i)=>`<li>${hits[i]?'✓':'○'} ${p}</li>`).join('');$('improveText').textContent=missing.length?`Develop these ideas more clearly: ${missing.slice(0,2).join(' ')}`:'Your response covered the main indicative points. Compare your wording with the mark points for precision.';$('feedbackPanel').hidden=false}
function skip(){const q=current();session.answers.push({id:q.id,ref:q.ref,topic:q.topic,ao:q.ao,marks:q.marks,score:0,answer:''});nextQuestion()}
function nextQuestion(){session.index++;if(session.index>=session.questions.length)finishSession();else renderQuestion()}
function finishSession(){if(!session)return;clearInterval(timerId);for(let i=session.answers.length;i<session.questions.length;i++){const q=session.questions[i];session.answers.push({id:q.id,ref:q.ref,topic:q.topic,ao:q.ao,marks:q.marks,score:0,answer:''})}const total=session.answers.reduce((s,a)=>s+a.marks,0),score=session.answers.reduce((s,a)=>s+a.score,0),pct=total?Math.round(score/total*100):0;const attempt={id:Date.now(),date:new Date().toISOString(),subject,mode:session.mode,score,total,pct,answers:session.answers};const h=history();h.unshift(attempt);localStorage.setItem(storeKey(subject),JSON.stringify(h.slice(0,50)));renderResult(attempt);session=null;updateIdentity();setView('resultView')}
function aggregateAnswers(attempts){return attempts.flatMap(a=>a.answers||[])}
function pctFor(arr){const m=arr.reduce((s,a)=>s+a.marks,0);return m?Math.round(arr.reduce((s,a)=>s+a.score,0)/m*100):0}
function renderResult(a){$('resultPercent').textContent=`${a.pct}%`;$('resultMarks').textContent=`${a.score} / ${a.total} marks`;$('resultTitle').textContent=`${subject[0].toUpperCase()+subject.slice(1)} practice result`;const answers=a.answers;$('aoResults').innerHTML=['AO1','AO2','AO3'].map(ao=>{const x=answers.filter(r=>r.ao===ao);return `<article class="ao-card"><strong>${pctFor(x)}%</strong><span>${ao} · ${x.length} question${x.length===1?'':'s'}</span></article>`}).join('');const byTopic=Object.entries(topics()).map(([k,v])=>({k,v,pct:pctFor(answers.filter(x=>x.topic===k)),n:answers.filter(x=>x.topic===k).length})).filter(x=>x.n).sort((a,b)=>b.pct-a.pct);$('strongAreas').innerHTML=(byTopic.slice(0,3).map(x=>`<li>${x.v} · ${x.pct}%</li>`).join('')||'<li>No scored areas yet.</li>');$('weakAreas').innerHTML=(byTopic.slice(-3).reverse().map(x=>`<li>${x.v} · ${x.pct}%</li>`).join('')||'<li>Complete more questions to identify priorities.</li>')}
function renderDashboard(){const h=history(),answers=aggregateAnswers(h);$('dashboardTitle').textContent=`${subject[0].toUpperCase()+subject.slice(1)} assessment progress`;$('dashboardStats').innerHTML=`<article class="dashboard-stat"><strong>${h.length}</strong><span>saved attempts</span></article><article class="dashboard-stat"><strong>${answers.length}</strong><span>questions answered</span></article><article class="dashboard-stat"><strong>${pctFor(answers)}%</strong><span>overall formative score</span></article>`;$('topicMastery').innerHTML=Object.entries(topics()).map(([k,v])=>{const a=answers.filter(x=>x.topic===k),p=pctFor(a);return `<article class="mastery-row"><div><strong>${k} · ${v}</strong><small>${a.length} answers</small></div><div class="mastery-track"><i style="width:${p}%"></i></div><strong>${p}%</strong></article>`}).join('')}
function renderHistory(){const h=history();$('historyList').innerHTML=h.length?h.map(a=>`<article class="history-row"><div><strong>${new Date(a.date).toLocaleDateString()}</strong><small>${a.mode} · ${(a.answers||[]).length} questions</small></div><div>${a.score} / ${a.total} marks</div><strong>${a.pct}%</strong></article>`).join(''):'<div class="empty-state">No saved attempts yet. Build a practice set to start your assessment history.</div>'}
function switchSubject(next){if(!['biology','chemistry'].includes(next)||next===subject)return;clearInterval(timerId);session=null;subject=next;history.replaceState?.(null,'',`?subject=${subject}`);const url=new URL(location.href);url.searchParams.set('subject',subject);window.history.replaceState(null,'',url);setView('setupView');updateIdentity()}
document.querySelectorAll('[data-subject]').forEach(b=>b.addEventListener('click',()=>switchSubject(b.dataset.subject)));
document.querySelectorAll('.side-nav').forEach(b=>b.addEventListener('click',()=>{setView(`${b.dataset.view}View`);if(b.dataset.view==='dashboard')renderDashboard();if(b.dataset.view==='history')renderHistory()}));
['modeSelect','topicSelect','aoSelect','countSelect','timedToggle','practicalToggle'].forEach(id=>$(id).addEventListener('change',updateSetupSummary));
$('startBtn').addEventListener('click',startSession);$('markBtn').addEventListener('click',markAnswer);$('skipBtn').addEventListener('click',skip);$('nextBtn').addEventListener('click',nextQuestion);$('retryBtn').addEventListener('click',()=>setView('setupView'));$('reviewBtn').addEventListener('click',()=>{renderDashboard();setView('dashboardView')});$('clearHistoryBtn').addEventListener('click',()=>{localStorage.removeItem(storeKey(subject));renderHistory();renderDashboard();updateIdentity();toast('Assessment history cleared')});
window.addEventListener('beforeunload',()=>clearInterval(timerId));updateIdentity();setView('setupView');
window.ALEVEL_ASSESSMENT_ENGINE=Object.freeze({getSubject:()=>subject,getBank:bank,start:startSession});
})();