(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qs=new URLSearchParams(location.search);
let subject=qs.get('subject')==='chemistry'?'chemistry':'biology';
let currentRef='';
const META={
 biology:{label:'Biology',code:'7402',content:()=>window.ALEVEL_BIOLOGY_CONTENT,hero:'Connect molecular, cellular, organism and ecosystem ideas in unfamiliar biological contexts.',master:'Plan a synoptic Paper 3 essay by selecting relevant biology from across the specification rather than writing everything you know.',masterTitle:'Biology Paper 3 essay mastery'},
 chemistry:{label:'Chemistry',code:'7405',content:()=>window.ALEVEL_CHEMISTRY_CONTENT,hero:'Connect physical, inorganic and organic chemistry to solve unfamiliar multi-step problems.',master:'Build a Paper 3 solution that combines practical evidence, quantitative chemistry and synoptic chemical reasoning.',masterTitle:'Chemistry Paper 3 synoptic mastery'}
};
const storeKey=()=>`alevel-${subject}-astar-hub-v1`;
const read=()=>{try{return JSON.parse(localStorage.getItem(storeKey()))||{attempts:{},master:0}}catch{return{attempts:{},master:0}}};
const write=s=>localStorage.setItem(storeKey(),JSON.stringify(s));
const data=()=>META[subject].content();
const refs=()=>data()?.refs||[];
const profile=ref=>data()?.get?.(ref)||null;
const major=ref=>String(ref).split('.').slice(0,2).join('.');
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1500)}
function otherRef(ref){const m=major(ref),pool=refs().filter(r=>major(r)!==m);return pool[Math.abs(ref.split('').reduce((a,c)=>a+c.charCodeAt(0),0))%Math.max(pool.length,1)]||refs()[0]}
function titleFor(ref){const p=profile(ref);return `${ref} · ${p?.q||'A* challenge'}`}
function setView(name){document.querySelectorAll('.view').forEach(v=>{const on=v.id===`${name}View`;v.hidden=!on;v.classList.toggle('active',on)});document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
function stats(){const s=read(),attempted=Object.keys(s.attempts||{}).length,total=refs().length,master=s.master||0;$('progressText').textContent=`${attempted} / ${total} section challenges attempted`;$('progressBar').style.width=`${total?attempted/total*100:0}%`;return{attempted,total,master}}
function renderDashboard(){const m=META[subject],d=data(),s=stats();document.title=`AQA A-Level ${m.label} A* Hub`;$('backLink').href=`../index.html?subject=${subject}`;$('brandTitle').textContent=`${m.label} A* Hub`;$('brandSub').textContent=`AQA ${m.code} · AO2/AO3 & synoptic reasoning`;$('heroEyebrow').textContent=`AQA ${m.label} ${m.code} · A* stretch`;$('heroTitle').textContent='Think across the specification.';$('heroText').textContent=m.hero;$('coverageCount').textContent=d?.count||0;$('stats').innerHTML=`<div class="stat"><strong>${s.attempted}</strong><span>section challenges attempted</span></div><div class="stat"><strong>${s.total}</strong><span>full-spec challenge sources</span></div><div class="stat"><strong>AO2</strong><span>unfamiliar-context application</span></div><div class="stat"><strong>AO3</strong><span>analysis, judgement & evaluation</span></div>`;
 $('refSelect').innerHTML=refs().map(r=>`<option value="${esc(r)}">${esc(titleFor(r))}</option>`).join('');if(!currentRef)currentRef=refs()[0]||'';$('refSelect').value=currentRef;
 $('topicGrid').innerHTML=refs().map(r=>{const p=profile(r),done=!!read().attempts?.[r];return `<article class="topic-card" data-ref="${esc(r)}"><small>${done?'Attempted ✓':'A* challenge'} · ${esc(r)}</small><strong>${esc(p?.q||r)}</strong><p>${esc((p?.syn||[])[0]||'Connect this section to another area of the specification.')}</p></article>`}).join('');document.querySelectorAll('[data-ref]').forEach(c=>c.onclick=()=>openRef(c.dataset.ref));}
function challengeCards(ref){const p=profile(ref)||{},link=otherRef(ref),lp=profile(link)||{},math=(p.maths||[])[0]||'Use appropriate quantitative or graphical evidence.',syn=(p.syn||[])[0]||`Connect this idea with ${link}.`;const context=subject==='biology'?`Researchers observe an unexpected change in a biological system related to: ${p.q||ref}. The pattern is real, but the mechanism is not stated.`:`A research chemist encounters an unfamiliar reaction or material whose behaviour depends on: ${p.q||ref}. Several familiar models could explain the observations.`;return [
 ['1 · Unfamiliar context','Select the governing science',`${context} Explain which ideas from ${ref} should be applied first and why.`],
 ['2 · Synoptic connection','Link a second topic',`${syn} Then make an explicit connection to ${link}: ${lp.q||'another specification area'}.`],
 ['3 · Quantitative/data reasoning','Use evidence, not assertion',math],
 ['4 · Assumptions & limits','Test the explanation',`Use this common trap as a warning: ${p.mis||'Do not overstate what the evidence proves.'} State one assumption and explain how violating it would change the conclusion.`]
 ]}
function renderChallenge(){const p=profile(currentRef)||{};$('challengeTitle').textContent=titleFor(currentRef);$('challengeQuestion').textContent=`Apply ${p.terms?.slice(0,3).join(', ')||'the section knowledge'} to an unfamiliar problem and connect the answer to evidence and another topic.`;$('challengeGrid').innerHTML=challengeCards(currentRef).map(([n,h,b])=>`<article class="challenge-card"><span>${esc(n)}</span><h3>${esc(h)}</h3><p>${esc(b)}</p></article>`).join('');$('challengeFeedback').innerHTML='';}
function renderEvidence(){const p=profile(currentRef)||{};$('evidenceIntro').textContent=`Evaluate a method or evidence set linked to ${currentRef}. A* responses separate what the evidence shows from what the researcher claims.`;const practical=p.practical||[],maths=p.maths||[];$('evidenceCase').innerHTML=`<h3>${esc(titleFor(currentRef))}</h3><div class="case-grid"><div class="case-box"><strong>Proposed investigation</strong><p>${esc(practical[0]||'Design an investigation that generates valid quantitative evidence.')}</p></div><div class="case-box"><strong>Evidence handling</strong><p>${esc(maths[0]||'Choose appropriate data processing and justify the display or calculation.')}</p></div><div class="case-box"><strong>Second practical link</strong><p>${esc(practical[1]||'Identify controls, repeats and an appropriate comparison.')}</p></div><div class="case-box"><strong>Claim to challenge</strong><p>${esc(p.mis||'A conclusion is stronger than the evidence allows.')}</p></div></div>`;$('evidenceFeedback').innerHTML='';}
function renderExtended(){const p=profile(currentRef)||{};$('extendedTitle').textContent=subject==='biology'?'A* biological extended response':'A* chemical extended response';$('extendedPrompt').textContent=subject==='biology'?`Explain how the ideas in ${currentRef} could interact with another area of biology to produce an observed phenotype, response or population-level outcome.`:`Explain how the ideas in ${currentRef} can be combined with another area of chemistry to predict or explain an unfamiliar observation.`;const link=otherRef(currentRef);$('extendedPlanner').innerHTML=`<h3>Plan before writing</h3><div class="planner-grid"><div class="plan-box"><strong>Core mechanism</strong><p>${esc((p.model||[]).join(' → ')||p.q||'State the central scientific sequence.')}</p></div><div class="plan-box"><strong>Precision vocabulary</strong><p>${esc((p.terms||[]).join(' · '))}</p></div><div class="plan-box"><strong>Synoptic link</strong><p>${esc(link)} · ${esc(profile(link)?.q||'another topic')}</p></div><div class="plan-box"><strong>Evidence</strong><p>${esc((p.practical||[])[0]||(p.maths||[])[0]||'Use relevant experimental or quantitative evidence.')}</p></div></div>`;$('extendedFeedback').innerHTML='';}
function masterRefs(){if(subject==='biology'){const groups=['3.1','3.2','3.3','3.4','3.5','3.6','3.7','3.8'];return groups.map(g=>refs().find(r=>major(r)===g)).filter(Boolean)}const phys=refs().find(r=>r.startsWith('3.1.')),ino=refs().find(r=>r.startsWith('3.2.')),org=refs().find(r=>r.startsWith('3.3.'));return [phys,ino,org].filter(Boolean)}
function renderMaster(){const m=META[subject],chosen=masterRefs();$('masterTitle').textContent=m.masterTitle;$('masterIntro').textContent=m.master;if(subject==='biology'){$('masterResponseTitle').textContent='Essay plan / opening paragraphs';$('masterTask').innerHTML=`<h3>Original 25-mark essay practice</h3><p><strong>Theme:</strong> Explain the importance of interactions and regulation in living systems.</p><p>Select only relevant biology. Aim for breadth across the course, accurate detail within each area, and explicit links back to the title.</p><div class="master-links">${chosen.map(r=>`<label><input type="checkbox" data-master-ref="${r}"><span><strong>${r}</strong> ${esc(profile(r)?.q||'')}</span></label>`).join('')}</div>`}else{$('masterResponseTitle').textContent='Synoptic solution plan';$('masterTask').innerHTML=`<h3>Original Paper 3 synoptic problem</h3><p>An unfamiliar industrial process gives an unexpected yield and a mixture containing an inorganic catalyst and an organic product. Build a solution that combines <strong>physical chemistry</strong>, <strong>inorganic evidence</strong> and <strong>organic analysis</strong>.</p><div class="master-links">${chosen.map(r=>`<label><input type="checkbox" data-master-ref="${r}"><span><strong>${r}</strong> ${esc(profile(r)?.q||'')}</span></label>`).join('')}</div>`}$('masterFeedback').innerHTML='';}
function checklist(type){const p=profile(currentRef)||{},terms=(p.terms||[]).slice(0,4);if(type==='challenge')return ['Select a scientifically valid starting principle or mechanism.','Apply it to the unfamiliar context rather than repeating notes.','Make at least one explicit cross-topic connection.','Use quantitative, practical or observational evidence where relevant.','State an assumption, limitation or alternative explanation.'];if(type==='evidence')return ['Identify a specific limitation rather than saying “human error”.','Explain how the limitation could change the result or conclusion.','Propose an improvement that directly addresses that limitation.','Distinguish correlation/observation from a causal conclusion.','Refer to repeats, controls, uncertainty or statistical/analytical evidence where relevant.'];if(type==='extended')return [`Use precise terms: ${terms.join(', ')||'subject-specific terminology'}.`,'Develop linked reasoning: cause → mechanism → consequence.','Use a second specification area synoptically.','Integrate evidence/calculation rather than bolting it on.','Reach a clear conclusion that answers the exact prompt.'];return subject==='biology'?['Use at least four distinct, relevant specification areas.','Explain each example in accurate biological detail.','Make explicit links back to the essay theme.','Prioritise depth and relevance over listing facts.','Use coherent paragraphs and scientific terminology.']:['Use physical, inorganic and organic chemistry together.','Show multi-step quantitative working where it helps the argument.','Use practical/analytical evidence to distinguish possible explanations.','State conditions, assumptions and limits of predictions.','Finish with a justified chemical conclusion.']}
function showFeedback(id,type,text){const items=checklist(type),enough=(text||'').trim().length>=120;$(id).innerHTML=`<strong>${enough?'Good depth to self-assess':'Develop the response further before self-assessing'}</strong><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
function saveAttempt(type){const s=read();s.attempts=s.attempts||{};s.attempts[currentRef]={...(s.attempts[currentRef]||{}),[type]:new Date().toISOString()};write(s);stats();toast('A* attempt saved')}
function saveMaster(){const s=read();s.master=(s.master||0)+1;write(s);stats();toast('Paper 3 attempt saved')}
function openRef(ref){currentRef=ref;renderChallenge();renderEvidence();renderExtended();setView('challenge');$('refSelect').value=ref}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='challenge')renderChallenge();if(v==='evidence')renderEvidence();if(v==='extended')renderExtended();if(v==='master')renderMaster();setView(v)});$('subjectSelect').onchange=()=>{subject=$('subjectSelect').value;currentRef='';history.replaceState(null,'',`?subject=${subject}`);initSubject()};$('refSelect').onchange=()=>currentRef=$('refSelect').value;$('openChallengeBtn').onclick=()=>openRef($('refSelect').value);$('randomBtn').onclick=()=>{const r=refs();openRef(r[Math.floor(Math.random()*r.length)])};$('challengeCheck').onclick=()=>showFeedback('challengeFeedback','challenge',$('challengeResponse').value);$('challengeSave').onclick=()=>saveAttempt('challenge');$('evidenceCheck').onclick=()=>showFeedback('evidenceFeedback','evidence',$('evidenceResponse').value);$('evidenceSave').onclick=()=>saveAttempt('evidence');$('extendedCheck').onclick=()=>showFeedback('extendedFeedback','extended',$('extendedResponse').value);$('extendedSave').onclick=()=>saveAttempt('extended');$('masterCheck').onclick=()=>showFeedback('masterFeedback','master',$('masterResponse').value);$('masterSave').onclick=saveMaster;}
function initSubject(){$('subjectSelect').value=subject;currentRef=refs()[0]||'';renderDashboard();renderChallenge();renderEvidence();renderExtended();renderMaster();setView('dashboard')}
function init(){bind();initSubject();window.ALEVEL_ASTAR_HUB=Object.freeze({version:'phase-14',subject:()=>subject,refs:()=>refs(),profile,openRef,progress:read});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();