(()=>{
'use strict';
const $=id=>document.getElementById(id);
const safe=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}};
const clamp=n=>Math.max(0,Math.min(1,Number(n)||0));
const pct=n=>Math.round(clamp(n)*100);
const SUBJECTS={
 physics:{label:'Physics',code:'7408',className:'physics',topicTotal:8,progress:'alevel-course-progress-v1',astar:'alevel-astar-progress-v1',supports:{assessment:false,practicals:false,skills:false,stretch:false},home:'../index.html?subject=physics'},
 biology:{label:'Biology',code:'7402',className:'biology',topicTotal:8,sectionTotal:39,progress:'alevel-biology-progress-v1',assessment:'alevel-biology-assessment-history-v1',practicals:'alevel-biology-required-practicals-v1',skills:'alevel-biology-data-coach-v1',astar:'alevel-biology-astar-hub-v1',skillTotal:10,supports:{assessment:true,practicals:true,skills:true,stretch:true},home:'../index.html?subject=biology'},
 chemistry:{label:'Chemistry',code:'7405',className:'chemistry',topicTotal:3,sectionTotal:34,progress:'alevel-chemistry-progress-v1',assessment:'alevel-chemistry-assessment-history-v1',practicals:'alevel-chemistry-required-practicals-v1',skills:'alevel-chemistry-calculation-coach-v1',astar:'alevel-chemistry-astar-hub-v1',skillTotal:14,supports:{assessment:true,practicals:true,skills:true,stretch:true},home:'../index.html?subject=chemistry'}
};
const TOOL_LINKS={
 biology:{assessment:'assessment-hub.html?subject=biology',practicals:'biology-practicals.html',skills:'biology-data-coach.html',stretch:'astar-hub.html?subject=biology'},
 chemistry:{assessment:'assessment-hub.html?subject=chemistry',practicals:'chemistry-practicals.html',skills:'chemistry-calculation-coach.html',stretch:'astar-hub.html?subject=chemistry'},
 physics:{coverage:'../index.html?subject=physics',stretch:'../index.html?subject=physics'}
};
function truthyCount(obj){if(!obj||typeof obj!=='object')return 0;return Object.values(obj).filter(Boolean).length}
function assessmentData(key){const attempts=safe(key,[]);const valid=Array.isArray(attempts)?attempts:[];const answers=valid.flatMap(a=>Array.isArray(a.answers)?a.answers:[]);const marks=answers.reduce((s,a)=>s+(Number(a.marks)||0),0),score=answers.reduce((s,a)=>s+(Number(a.score)||0),0);return{attempts:valid,answers,ratio:marks?score/marks:0,marks,score}}
function practicalData(key){const x=safe(key,[]);const done=Array.isArray(x)?new Set(x.map(Number).filter(Number.isFinite)).size:Array.isArray(x?.done)?new Set(x.done).size:0;return{done,total:12,ratio:done/12}}
function skillData(key,total){const x=safe(key,{skills:[],practice:0});const skills=Array.isArray(x?.skills)?new Set(x.skills).size:0;return{done:skills,total,ratio:total?skills/total:0,practice:Number(x?.practice)||0}}
function stretchData(key,total){const x=safe(key,{});if(x&&typeof x==='object'&&x.attempts&&typeof x.attempts==='object'){const done=Object.keys(x.attempts).length;return{done,total,ratio:total?done/total:0,master:Number(x.master)||0}}const done=x&&typeof x==='object'?Object.values(x).filter(v=>v&&((typeof v==='object'&&v.attempted)||v===true)).length:0;return{done,total:0,ratio:0,master:0}}
function courseData(cfg){const p=safe(cfg.progress,{});const done=truthyCount(p);return{done,total:cfg.topicTotal,ratio:cfg.topicTotal?done/cfg.topicTotal:0}}
function subjectData(id){const cfg=SUBJECTS[id],course=courseData(cfg),assessment=cfg.supports.assessment?assessmentData(cfg.assessment):null,practicals=cfg.supports.practicals?practicalData(cfg.practicals):null,skills=cfg.supports.skills?skillData(cfg.skills,cfg.skillTotal):null,stretch=cfg.supports.stretch?stretchData(cfg.astar,cfg.sectionTotal):stretchData(cfg.astar,0);const metrics=[{id:'coverage',label:'Course coverage',ratio:course.ratio,weight:cfg.supports.assessment?.35:1,available:true,data:course},{id:'assessment',label:'Assessment mastery',ratio:assessment?.ratio||0,weight:.35,available:cfg.supports.assessment,data:assessment},{id:'practicals',label:'Required practicals',ratio:practicals?.ratio||0,weight:.15,available:cfg.supports.practicals,data:practicals},{id:'skills',label:id==='biology'?'Data skills':'Calculation skills',ratio:skills?.ratio||0,weight:.10,available:cfg.supports.skills,data:skills},{id:'stretch',label:'A* stretch',ratio:stretch?.ratio||0,weight:.05,available:cfg.supports.stretch,data:stretch}];const active=metrics.filter(m=>m.available),weight=active.reduce((s,m)=>s+m.weight,0)||1,mastery=active.reduce((s,m)=>s+m.ratio*m.weight,0)/weight;return{id,cfg,course,assessment,practicals,skills,stretch,metrics,mastery,evidence:active.filter(m=>m.ratio>0).length,available:active.length}}
function collect(){return Object.fromEntries(Object.keys(SUBJECTS).map(id=>[id,subjectData(id)]))}
function signalClass(r){return r>=.75?'good':r>=.4?'mid':'low'}
function renderSummary(data){const arr=Object.values(data),overall=arr.reduce((s,x)=>s+x.mastery,0)/arr.length,totalTopics=arr.reduce((s,x)=>s+x.course.total,0),doneTopics=arr.reduce((s,x)=>s+x.course.done,0),assessmentAttempts=arr.reduce((s,x)=>s+(x.assessment?.attempts.length||0),0),practicals=arr.reduce((s,x)=>s+(x.practicals?.done||0),0);$('overallScore').textContent=`${pct(overall)}%`;$('summaryGrid').innerHTML=`<article class="summary-card"><strong>${doneTopics}/${totalTopics}</strong><span>course topics complete</span></article><article class="summary-card"><strong>${assessmentAttempts}</strong><span>saved Biology/Chemistry assessments</span></article><article class="summary-card"><strong>${practicals}/24</strong><span>Biology + Chemistry required practicals</span></article><article class="summary-card"><strong>${arr.reduce((s,x)=>s+(x.stretch?.done||0),0)}</strong><span>A* section challenges attempted</span></article>`;return overall}
function metricText(m){if(m.id==='coverage')return`${m.data.done}/${m.data.total}`;if(m.id==='assessment')return m.data?.answers.length?`${pct(m.ratio)}%`:'No attempts';if(m.id==='practicals')return`${m.data.done}/12`;if(m.id==='skills')return`${m.data.done}/${m.data.total}`;if(m.id==='stretch')return`${m.data.done}/${m.data.total}`;return'—'}
function renderSubjects(data){$('subjectGrid').innerHTML=Object.values(data).map(s=>`<article class="subject-card ${s.cfg.className}"><div class="subject-top"><div><span class="eyebrow">AQA ${s.cfg.code}</span><h3>${s.cfg.label}</h3></div><div class="score-ring" style="--score:${pct(s.mastery)}"><b>${pct(s.mastery)}%</b></div></div>${s.metrics.filter(m=>m.available).map(m=>`<div class="meter-row"><span>${m.label}</span><div class="track"><i style="width:${pct(m.ratio)}%"></i></div><b>${metricText(m)}</b></div>`).join('')}<div class="subject-meta"><span class="chip">${s.evidence}/${s.available} active evidence strands</span>${s.id==='physics'?`<span class="chip">Physics external marking/practicals remain separate</span>`:''}</div></article>`).join('')}
function aggregateAO(data){const answers=Object.values(data).flatMap(s=>s.assessment?.answers||[]);return['AO1','AO2','AO3'].map(ao=>{const x=answers.filter(a=>a.ao===ao),marks=x.reduce((s,a)=>s+(Number(a.marks)||0),0),score=x.reduce((s,a)=>s+(Number(a.score)||0),0);return{ao,n:x.length,ratio:marks?score/marks:0}})}
function renderAO(data){$('aoGrid').innerHTML=aggregateAO(data).map(x=>`<article class="ao-card"><strong>${x.n?pct(x.ratio)+'%':'—'}</strong><span>${x.ao} · ${x.n} answers</span></article>`).join('')}
function priorityActions(data){const actions=[];for(const s of Object.values(data)){const label=s.cfg.label;if(s.course.ratio<1)actions.push({gap:1-s.course.ratio,subject:s.id,title:`Continue ${label} course coverage`,detail:`${s.course.done} of ${s.course.total} main topics complete`,href:s.cfg.home});if(s.cfg.supports.assessment&&(s.assessment.answers.length===0||s.assessment.ratio<.7))actions.push({gap:s.assessment.answers.length?1-s.assessment.ratio:1.05,subject:s.id,title:`Build ${label} assessment evidence`,detail:s.assessment.answers.length?`${pct(s.assessment.ratio)}% across ${s.assessment.answers.length} answers`:'No saved assessment attempt yet',href:TOOL_LINKS[s.id].assessment});if(s.practicals&&s.practicals.ratio<1)actions.push({gap:(1-s.practicals.ratio)*.65,subject:s.id,title:`Complete ${label} practical evidence`,detail:`${s.practicals.done} of 12 required practicals complete`,href:TOOL_LINKS[s.id].practicals});if(s.skills&&s.skills.ratio<1)actions.push({gap:(1-s.skills.ratio)*.5,subject:s.id,title:`Practise ${label} quantitative skills`,detail:`${s.skills.done} of ${s.skills.total} coach skills practised`,href:TOOL_LINKS[s.id].skills});if(s.stretch&&s.cfg.supports.stretch&&s.stretch.ratio<.5)actions.push({gap:(.5-s.stretch.ratio)*.35,subject:s.id,title:`Add ${label} A* application`,detail:`${s.stretch.done} of ${s.stretch.total} specification challenges attempted`,href:TOOL_LINKS[s.id].stretch})}return actions.sort((a,b)=>b.gap-a.gap).slice(0,5)}
function renderPriorities(data){const actions=priorityActions(data);$('priorityList').innerHTML=actions.length?actions.map((a,i)=>`<div class="priority-item"><span class="priority-n">${i+1}</span><div><strong>${a.title}</strong><small>${a.detail}</small></div><a href="${a.href}">Open →</a></div>`).join(''):'<div class="empty">No major gaps detected in the recorded evidence. Keep using mixed Paper 3 and A* practice.</div>'}
function renderMatrix(data){const rows=['coverage','assessment','practicals','skills','stretch'];$('matrix').innerHTML=`<table><thead><tr><th>Evidence</th>${Object.values(data).map(s=>`<th>${s.cfg.label}</th>`).join('')}</tr></thead><tbody>${rows.map(id=>`<tr><td><strong>${{coverage:'Course coverage',assessment:'Assessment',practicals:'Required practicals',skills:'Quantitative/data skills',stretch:'A* stretch'}[id]}</strong></td>${Object.values(data).map(s=>{const m=s.metrics.find(x=>x.id===id);if(!m?.available){const count=id==='stretch'&&s.id==='physics'&&s.stretch.done?`${s.stretch.done} lesson A* attempts`:'Not recorded in this app';return`<td><span class="signal"><i class="dot"></i>${count}</span></td>`}return`<td><span class="signal"><i class="dot ${signalClass(m.ratio)}"></i>${metricText(m)}</span></td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function assessedAreas(data){const out=[];for(const s of Object.values(data)){if(!s.assessment)continue;const groups={};for(const a of s.assessment.answers){const key=a.ref||a.topic||'Other';groups[key]??={marks:0,score:0,n:0};groups[key].marks+=Number(a.marks)||0;groups[key].score+=Number(a.score)||0;groups[key].n++}for(const [ref,g] of Object.entries(groups)){out.push({subject:s.cfg.label,id:s.id,ref,n:g.n,ratio:g.marks?g.score/g.marks:0})}}return out.sort((a,b)=>a.ratio-b.ratio||b.n-a.n).slice(0,6)}
function renderWeak(data){const areas=assessedAreas(data);$('weakAreas').innerHTML=areas.length?areas.map(x=>`<div class="weak-item"><i class="dot ${signalClass(x.ratio)}"></i><div><strong>${x.subject} · ${x.ref}</strong><small>${x.n} assessed response${x.n===1?'':'s'}</small></div><strong>${pct(x.ratio)}%</strong></div>`).join(''):'<div class="empty">Complete Biology or Chemistry assessment sets to generate topic-level diagnosis.</div>'}
function renderRecent(data){const attempts=Object.values(data).flatMap(s=>(s.assessment?.attempts||[]).map(a=>({...a,subject:s.cfg.label}))).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,6);$('recentAttempts').innerHTML=attempts.length?attempts.map(a=>`<div class="recent-item"><i class="dot ${signalClass((Number(a.pct)||0)/100)}"></i><div><strong>${a.subject} · ${a.mode||'practice'}</strong><small>${a.date?new Date(a.date).toLocaleDateString():'Saved attempt'} · ${(a.answers||[]).length} questions</small></div><strong>${Number(a.pct)||0}%</strong></div>`).join(''):'<div class="empty">No Biology or Chemistry assessment history yet.</div>'}
function render(){const data=collect();renderSummary(data);renderSubjects(data);renderAO(data);renderPriorities(data);renderMatrix(data);renderWeak(data);renderRecent(data);$('methodText').textContent='Biology and Chemistry use 35% course coverage, 35% internal assessment evidence, 15% required practicals, 10% quantitative/data coach practice and 5% A* stretch. Physics currently uses its recorded course completion as the readiness score because its marking and practical apps are external to this origin; Physics A* attempts are shown as supporting evidence without being turned into an artificial percentage.';window.ALEVEL_PROGRESS_MASTERY.last=data;return data}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1500)}
const from=new URLSearchParams(location.search).get('from');if(['physics','biology','chemistry'].includes(from))$('backLink').href=`../index.html?subject=${from}`;$('refreshBtn').addEventListener('click',()=>{render();toast('Progress refreshed')});window.addEventListener('storage',render);window.addEventListener('focus',render);
window.ALEVEL_PROGRESS_MASTERY={version:'phase-15',collect,render,subjects:SUBJECTS};render();
})();